package console

import (
	"fmt"

	"github.com/evilsocket/islazy/tui"
	"github.com/maxlandon/wiregost/client/assets"
	"github.com/maxlandon/wiregost/client/context"
	clientpb "github.com/maxlandon/wiregost/proto/v1/gen/go/client"
)

// PrintBanner - Print Wiregost banner, client & server information, etc.
func (c *console) PrintBanner(ver *clientpb.Version, info *clientpb.ConnectionInfo) {

	// Setup all strings needed
	userStr := fmt.Sprintf("Connected as user: %s%s%s", tui.YELLOW, context.Context.User.Name, tui.RESET)
	// userStr := fmt.Sprintf("%-82vConnected as user: %s%s", 82, tui.YELLOW, context.Context.User.Name)
	user := fmt.Sprintf("%-91s", userStr)
	serverStr := fmt.Sprintf("Server address: %s%s:%d%s", tui.YELLOW, assets.ServerConfig.LHost, assets.ServerConfig.LPort, tui.RESET)
	server := fmt.Sprintf("%-91s", serverStr)

	cliVerStr := fmt.Sprintf("Client version: %s%s.%s.%s%s", tui.YELLOW, ver.ClientMajor, ver.ClientMinor, ver.ClientPatch, tui.RESET)
	cliVer := fmt.Sprintf("%-91s", cliVerStr)
	serVerStr := fmt.Sprintf("Server version: %s%s.%s.%s%s", tui.YELLOW, ver.ServerMajor, ver.ServerMinor, ver.ServerPatch, tui.RESET)
	serVer := fmt.Sprintf("%-91s", serVerStr)
	gitStr := fmt.Sprintf("Server commit tag: %s%s%s", tui.YELLOW, ver.ServerCommitTag, tui.RESET)
	git := fmt.Sprintf("%-91s", gitStr)

	dbStr := fmt.Sprintf("Connected to DB: %sok%s (%s%s:%d%s)", tui.GREEN, tui.RESET, tui.YELLOW, info.DBHost, int(info.DBPort), tui.RESET)
	db := fmt.Sprintf("%-100s", dbStr)
	confStr := fmt.Sprintf("Console configuration: %sok%s", tui.GREEN, tui.RESET)
	conf := fmt.Sprintf("%-91s", confStr)

	// Setup banners
	var bannerServerConnection = fmt.Sprintf(`                                                                                                            ,,.,=++============+,               
                                                                                                       ,+==========================..           
                                                                                           ... ........===============================..:,,,,,,.
#                          ,,                                                             ..  .....=.==================================.,,=,,,..
#  '7MMF'     A     '7MF'  db                      .g8"""bgd                      mm     ...........=:~==~~=========================~=.:,...=...
#    'MA     ,MA     ,V                          .dP'     'M                      MM     .......=..=.,:=====~~=======================:=,,.......
#     VM:   ,VVM:   ,V   '7MM  '7Mb,od8  .gP"Ya  dM'       '   ,pW"Wq.  ,pP"Ybd mmMMmm   ......,..:.==.~~~==~~~======================,..=...,...
#      MM.  M' MM.  M'     MM    MM' "' ,M'   Yb MM           6W'   'Wb 8I   '"   MM    .....,..=..=...~===~=~~~~====================.~...=.....
#      'MM A'  'MM A'      MM    MM     8M"""""" MM.    '7MMF'8M     M8 'YMMMa.   MM    ..........:.,=.~=~~=~~~~~~==================~..,=.......
#       :MM;    :MM;       MM    MM     YM.    , 'Mb.     MM  YA.   ,A9 L.   I8   MM    ........=..~...~~~~=~~~~~~~~=================,:+........
#        VF      VF      .JMML..JMML.    'Mbmmd'   '"bmmmdPY   'Ybmd9'  M9mmmP'   'Mbmo......=..~..~..~~~~~~~~~~~~~~~~~=============~~.?,.,.....
                                                                                     ........:.....=.~~~~~~~~~~~~~~~~~~~~~===============.,.....
                                                                                    . .............~~.....~~~~~~~~~~~~~~~~~~=====:.,,.~==,......
                        A Golang Exploitation Framework                              .............,.,.........:+=~~~~~~~~~~~=......,,,,,,=,.....
         __________________________________________________________________         ...............................~~.~~=~........,,,,,,,,+,,...
                                                                                     ..........,...................=.~~~:.........,,,,,,,,,,,...
                                                                                    ................................:.~~~.........,,,,,,,,,~=...
                                                                                       .....::.....................~.=~~~~~.......,,,,,,,,,,.=~.
    " If you think technololy can solve your security problems, then you              .........=..+..........~...:,.~..,~.:~=.+.,,,,,,,,~+:.==..
      don't understand the problems and you don't understand the technology. "         ......=..?=..~=,=,.~..,.~=.......~~,.~~~~~=~~=~=~====...=
                                                                                          ..........,......+..=.+,.......:==.,=====~==,=.,,.....
                                                - Bruce Schneier -                        ...................=,,+:......,.:.=+,++.=,,,.,.,,.=...
                                                                                          .................=..,............=..~.,.~,,,..,,,,,...
                                                                                          ............,......+,.=....,,...+,=~.:~,,,,..,,,......
        %s...........?..~..:.....=,..+.....=..~...,,,,...,......
        %s.............,......,.=.:==.==.=+.~~,..,,,,,,=,.......
                                                                                          ........................=..~..==.,=..:................
        %s......................:...+.~=.,~.....................
        %s........................=.,=,.~:.=...~................
        %s.........................==.,=..=.....:...............
                                                                                          .....................~..=,.=......:...................
`, user, server, cliVer, serVer, git)

	var bannerDatabaseConnection = fmt.Sprintf(`        %s......................,~....:...~~....................
        %s......................................................
`, db, conf)

	// Print banners
	fmt.Printf(bannerServerConnection)
	fmt.Println(bannerDatabaseConnection)
}
