// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_manager.proto

package core

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//-------------------------------
// ConnectUser
type ConnectRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{0}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

type ConnectResponse struct {
	Clearance            string   `protobuf:"bytes,1,opt,name=clearance,proto3" json:"clearance,omitempty"`
	Admin                bool     `protobuf:"varint,2,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{1}
}

func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (m *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(m, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

func (m *ConnectResponse) GetClearance() string {
	if m != nil {
		return m.Clearance
	}
	return ""
}

func (m *ConnectResponse) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

//-------------------------------
// DisconnectUser
type DisconnectRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{2}
}

func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(m, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

type DisconnectResponse struct {
	Disconnected         bool     `protobuf:"varint,1,opt,name=disconnected,proto3" json:"disconnected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{3}
}

func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (m *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(m, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

func (m *DisconnectResponse) GetDisconnected() bool {
	if m != nil {
		return m.Disconnected
	}
	return false
}

//-------------------------------
// ListUsers
type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{4}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

// Each user listed
type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Connected            bool     `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	Admin                bool     `protobuf:"varint,3,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

func (m *User) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type ListUsersResponse struct {
	Clearance            string   `protobuf:"bytes,1,opt,name=clearance,proto3" json:"clearance,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{6}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetClearance() string {
	if m != nil {
		return m.Clearance
	}
	return ""
}

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

//-------------------------------
// CreateUser
type CreateUserRequest struct {
	Clearance            string   `protobuf:"bytes,1,opt,name=clearance,proto3" json:"clearance,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Admin                bool     `protobuf:"varint,3,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{7}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetClearance() string {
	if m != nil {
		return m.Clearance
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type CreateUserResponse struct {
	Clearance            string   `protobuf:"bytes,1,opt,name=clearance,proto3" json:"clearance,omitempty"`
	Created              bool     `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{8}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetClearance() string {
	if m != nil {
		return m.Clearance
	}
	return ""
}

func (m *CreateUserResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

//-------------------------------
// DeleteUser
type DeleteUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{9}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteUserResponse struct {
	Clearance            string   `protobuf:"bytes,1,opt,name=clearance,proto3" json:"clearance,omitempty"`
	Deleted              bool     `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{10}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetClearance() string {
	if m != nil {
		return m.Clearance
	}
	return ""
}

func (m *DeleteUserResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

//-------------------------------
// GiveAdminRights
type AdminRightsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminRightsRequest) Reset()         { *m = AdminRightsRequest{} }
func (m *AdminRightsRequest) String() string { return proto.CompactTextString(m) }
func (*AdminRightsRequest) ProtoMessage()    {}
func (*AdminRightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{11}
}

func (m *AdminRightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRightsRequest.Unmarshal(m, b)
}
func (m *AdminRightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRightsRequest.Marshal(b, m, deterministic)
}
func (m *AdminRightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRightsRequest.Merge(m, src)
}
func (m *AdminRightsRequest) XXX_Size() int {
	return xxx_messageInfo_AdminRightsRequest.Size(m)
}
func (m *AdminRightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRightsRequest proto.InternalMessageInfo

func (m *AdminRightsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AdminRightsResponse struct {
	Clearance            string   `protobuf:"bytes,1,opt,name=clearance,proto3" json:"clearance,omitempty"`
	Given                bool     `protobuf:"varint,2,opt,name=given,proto3" json:"given,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminRightsResponse) Reset()         { *m = AdminRightsResponse{} }
func (m *AdminRightsResponse) String() string { return proto.CompactTextString(m) }
func (*AdminRightsResponse) ProtoMessage()    {}
func (*AdminRightsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a765503409e8da8f, []int{12}
}

func (m *AdminRightsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRightsResponse.Unmarshal(m, b)
}
func (m *AdminRightsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRightsResponse.Marshal(b, m, deterministic)
}
func (m *AdminRightsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRightsResponse.Merge(m, src)
}
func (m *AdminRightsResponse) XXX_Size() int {
	return xxx_messageInfo_AdminRightsResponse.Size(m)
}
func (m *AdminRightsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRightsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRightsResponse proto.InternalMessageInfo

func (m *AdminRightsResponse) GetClearance() string {
	if m != nil {
		return m.Clearance
	}
	return ""
}

func (m *AdminRightsResponse) GetGiven() bool {
	if m != nil {
		return m.Given
	}
	return false
}

func init() {
	proto.RegisterType((*ConnectRequest)(nil), "core.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "core.ConnectResponse")
	proto.RegisterType((*DisconnectRequest)(nil), "core.DisconnectRequest")
	proto.RegisterType((*DisconnectResponse)(nil), "core.DisconnectResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "core.ListUsersRequest")
	proto.RegisterType((*User)(nil), "core.User")
	proto.RegisterType((*ListUsersResponse)(nil), "core.ListUsersResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "core.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "core.CreateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "core.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "core.DeleteUserResponse")
	proto.RegisterType((*AdminRightsRequest)(nil), "core.AdminRightsRequest")
	proto.RegisterType((*AdminRightsResponse)(nil), "core.AdminRightsResponse")
}

func init() { proto.RegisterFile("user_manager.proto", fileDescriptor_a765503409e8da8f) }

var fileDescriptor_a765503409e8da8f = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x41, 0xaf, 0xd2, 0x40,
	0x10, 0xa6, 0xc0, 0xd3, 0xc7, 0x60, 0xde, 0x7b, 0x1d, 0x50, 0x6a, 0xe3, 0xa1, 0xd9, 0x8b, 0x3d,
	0x11, 0x83, 0x17, 0x0f, 0x1e, 0x24, 0x40, 0xd4, 0x04, 0x3d, 0xd4, 0x78, 0xf2, 0x60, 0x6a, 0x3b,
	0xc1, 0x26, 0xd0, 0x62, 0xb7, 0xf0, 0x8b, 0xfc, 0xa1, 0x66, 0x77, 0xbb, 0xdb, 0x96, 0x12, 0x5f,
	0x6f, 0x9d, 0x6f, 0x67, 0xbf, 0xf9, 0x66, 0xe7, 0x9b, 0x02, 0x9e, 0x38, 0xe5, 0x3f, 0x0f, 0x61,
	0x1a, 0xee, 0x28, 0x9f, 0x1f, 0xf3, 0xac, 0xc8, 0x70, 0x18, 0x65, 0x39, 0xb1, 0x07, 0xb8, 0x5b,
	0x65, 0x69, 0x4a, 0x51, 0x11, 0xd0, 0x9f, 0x13, 0xf1, 0x82, 0x6d, 0xe0, 0xde, 0x20, 0xfc, 0x98,
	0xa5, 0x9c, 0xf0, 0x15, 0x8c, 0xa2, 0x3d, 0x85, 0x79, 0x98, 0x46, 0xe4, 0x58, 0x9e, 0xe5, 0x8f,
	0x82, 0x0a, 0xc0, 0x29, 0xdc, 0x84, 0xf1, 0x21, 0x49, 0x9d, 0xbe, 0x67, 0xf9, 0xb7, 0x81, 0x0a,
	0xd8, 0x04, 0xec, 0x75, 0xc2, 0xa3, 0x26, 0xf7, 0x3b, 0xc0, 0x3a, 0x58, 0xd2, 0x33, 0x78, 0x16,
	0x1b, 0x94, 0x62, 0x59, 0xe1, 0x36, 0x68, 0x60, 0x0c, 0xe1, 0x61, 0x9b, 0xf0, 0xe2, 0x3b, 0xa7,
	0x9c, 0x6b, 0xb6, 0xaf, 0x30, 0x14, 0x31, 0x22, 0x0c, 0xd3, 0xf0, 0xa0, 0x95, 0xc9, 0x6f, 0x29,
	0xd9, 0x10, 0x2a, 0x61, 0x15, 0x50, 0x49, 0x1e, 0xd4, 0x25, 0x7f, 0x03, 0xbb, 0x56, 0xa3, 0x53,
	0xef, 0x1e, 0xdc, 0x88, 0xa7, 0xe5, 0x4e, 0xdf, 0x1b, 0xf8, 0xe3, 0x05, 0xcc, 0xc5, 0xa3, 0xce,
	0x05, 0x43, 0xa0, 0x0e, 0xd8, 0x0f, 0xb0, 0x57, 0x39, 0x85, 0x05, 0x49, 0x50, 0x29, 0x7f, 0x84,
	0x54, 0xf7, 0xd3, 0xaf, 0xf5, 0x73, 0x5d, 0xf1, 0x16, 0xb0, 0x4e, 0xde, 0x49, 0xb2, 0x03, 0x4f,
	0x23, 0x79, 0x27, 0x2e, 0xb9, 0x74, 0xc8, 0x5e, 0x83, 0xbd, 0xa6, 0x3d, 0x35, 0xa5, 0x5e, 0x79,
	0x5c, 0x51, 0xb6, 0x9e, 0xd8, 0xb5, 0x6c, 0x2c, 0xef, 0xe8, 0x71, 0xe8, 0x90, 0xf9, 0x80, 0x4b,
	0xd1, 0x4d, 0x90, 0xec, 0x7e, 0x17, 0xfc, 0x7f, 0x75, 0x3f, 0xc3, 0xa4, 0x91, 0xd9, 0xd5, 0x9e,
	0xbb, 0xe4, 0x4c, 0xc6, 0x9e, 0x32, 0x58, 0xfc, 0x1d, 0xc0, 0x58, 0xa8, 0xff, 0xa2, 0x76, 0x02,
	0xdf, 0xc3, 0xb8, 0x74, 0xbd, 0xb4, 0xd4, 0x54, 0x0d, 0xb2, 0xb9, 0x1a, 0xee, 0xf3, 0x0b, 0x54,
	0xd5, 0x67, 0x3d, 0xdc, 0xc0, 0x5d, 0xe5, 0x6b, 0x49, 0x30, 0x53, 0xa9, 0xad, 0x15, 0x70, 0x9d,
	0xf6, 0x81, 0xa1, 0xf9, 0x00, 0x23, 0x63, 0x40, 0x7c, 0xa1, 0x12, 0x2f, 0x5d, 0xef, 0xce, 0x5a,
	0xb8, 0xbe, 0xff, 0xc6, 0xc2, 0x25, 0x40, 0x65, 0x08, 0x2d, 0xa2, 0xe5, 0x3f, 0x2d, 0xa2, 0xed,
	0x1d, 0xd6, 0x13, 0x14, 0xd5, 0x70, 0x4d, 0x1f, 0x97, 0xbe, 0x30, 0x7d, 0xb4, 0x7c, 0xc0, 0x7a,
	0xf8, 0x09, 0xee, 0x3f, 0x26, 0x67, 0xaa, 0xcd, 0x0a, 0xcb, 0xf4, 0xf6, 0xa0, 0xdd, 0x97, 0x57,
	0x4e, 0x34, 0xd3, 0xaf, 0x27, 0xf2, 0x5f, 0xf5, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00,
	0x9c, 0xcf, 0x1b, 0xc1, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserManagerClient is the client API for UserManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserManagerClient interface {
	// Notify connection
	ConnectUser(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	DisconnectUser(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// User management commands
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (UserManager_ListUsersClient, error)
	// ADMIN User management commands
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	GiveAdminRights(ctx context.Context, in *AdminRightsRequest, opts ...grpc.CallOption) (*AdminRightsResponse, error)
}

type userManagerClient struct {
	cc *grpc.ClientConn
}

func NewUserManagerClient(cc *grpc.ClientConn) UserManagerClient {
	return &userManagerClient{cc}
}

func (c *userManagerClient) ConnectUser(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/core.UserManager/ConnectUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerClient) DisconnectUser(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, "/core.UserManager/DisconnectUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (UserManager_ListUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserManager_serviceDesc.Streams[0], "/core.UserManager/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userManagerListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserManager_ListUsersClient interface {
	Recv() (*ListUsersResponse, error)
	grpc.ClientStream
}

type userManagerListUsersClient struct {
	grpc.ClientStream
}

func (x *userManagerListUsersClient) Recv() (*ListUsersResponse, error) {
	m := new(ListUsersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userManagerClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/core.UserManager/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/core.UserManager/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerClient) GiveAdminRights(ctx context.Context, in *AdminRightsRequest, opts ...grpc.CallOption) (*AdminRightsResponse, error) {
	out := new(AdminRightsResponse)
	err := c.cc.Invoke(ctx, "/core.UserManager/GiveAdminRights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagerServer is the server API for UserManager service.
type UserManagerServer interface {
	// Notify connection
	ConnectUser(context.Context, *ConnectRequest) (*ConnectResponse, error)
	DisconnectUser(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// User management commands
	ListUsers(*ListUsersRequest, UserManager_ListUsersServer) error
	// ADMIN User management commands
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GiveAdminRights(context.Context, *AdminRightsRequest) (*AdminRightsResponse, error)
}

// UnimplementedUserManagerServer can be embedded to have forward compatible implementations.
type UnimplementedUserManagerServer struct {
}

func (*UnimplementedUserManagerServer) ConnectUser(ctx context.Context, req *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectUser not implemented")
}
func (*UnimplementedUserManagerServer) DisconnectUser(ctx context.Context, req *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectUser not implemented")
}
func (*UnimplementedUserManagerServer) ListUsers(req *ListUsersRequest, srv UserManager_ListUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedUserManagerServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserManagerServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserManagerServer) GiveAdminRights(ctx context.Context, req *AdminRightsRequest) (*AdminRightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveAdminRights not implemented")
}

func RegisterUserManagerServer(s *grpc.Server, srv UserManagerServer) {
	s.RegisterService(&_UserManager_serviceDesc, srv)
}

func _UserManager_ConnectUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServer).ConnectUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.UserManager/ConnectUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServer).ConnectUser(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManager_DisconnectUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServer).DisconnectUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.UserManager/DisconnectUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServer).DisconnectUser(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManager_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserManagerServer).ListUsers(m, &userManagerListUsersServer{stream})
}

type UserManager_ListUsersServer interface {
	Send(*ListUsersResponse) error
	grpc.ServerStream
}

type userManagerListUsersServer struct {
	grpc.ServerStream
}

func (x *userManagerListUsersServer) Send(m *ListUsersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _UserManager_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.UserManager/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManager_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.UserManager/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManager_GiveAdminRights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServer).GiveAdminRights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.UserManager/GiveAdminRights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServer).GiveAdminRights(ctx, req.(*AdminRightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.UserManager",
	HandlerType: (*UserManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectUser",
			Handler:    _UserManager_ConnectUser_Handler,
		},
		{
			MethodName: "DisconnectUser",
			Handler:    _UserManager_DisconnectUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserManager_CreateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserManager_DeleteUser_Handler,
		},
		{
			MethodName: "GiveAdminRights",
			Handler:    _UserManager_GiveAdminRights_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _UserManager_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "user_manager.proto",
}
