// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package clientpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GhostConfig_OutputFormat int32

const (
	GhostConfig_SHARED_LIB GhostConfig_OutputFormat = 0
	GhostConfig_SHELLCODE  GhostConfig_OutputFormat = 1
	GhostConfig_EXECUTABLE GhostConfig_OutputFormat = 2
)

var GhostConfig_OutputFormat_name = map[int32]string{
	0: "SHARED_LIB",
	1: "SHELLCODE",
	2: "EXECUTABLE",
}

var GhostConfig_OutputFormat_value = map[string]int32{
	"SHARED_LIB": 0,
	"SHELLCODE":  1,
	"EXECUTABLE": 2,
}

func (x GhostConfig_OutputFormat) String() string {
	return proto.EnumName(GhostConfig_OutputFormat_name, int32(x))
}

func (GhostConfig_OutputFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{21, 0}
}

type EggConfig_EggProtocol int32

const (
	EggConfig_TCP   EggConfig_EggProtocol = 0
	EggConfig_HTTP  EggConfig_EggProtocol = 1
	EggConfig_HTTPS EggConfig_EggProtocol = 2
)

var EggConfig_EggProtocol_name = map[int32]string{
	0: "TCP",
	1: "HTTP",
	2: "HTTPS",
}

var EggConfig_EggProtocol_value = map[string]int32{
	"TCP":   0,
	"HTTP":  1,
	"HTTPS": 2,
}

func (x EggConfig_EggProtocol) String() string {
	return proto.EnumName(EggConfig_EggProtocol_name, int32(x))
}

func (EggConfig_EggProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{36, 0}
}

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Process struct {
	Pid                  int32    `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid                 int32    `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Executable           string   `protobuf:"bytes,3,opt,name=executable,proto3" json:"executable,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Process) GetPpid() int32 {
	if m != nil {
		return m.Ppid
	}
	return 0
}

func (m *Process) GetExecutable() string {
	if m != nil {
		return m.Executable
	}
	return ""
}

func (m *Process) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type Job struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Protocol             string   `protobuf:"bytes,4,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	Port                 int32    `protobuf:"varint,5,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Job) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type JobKillReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobKillReq) Reset()         { *m = JobKillReq{} }
func (m *JobKillReq) String() string { return proto.CompactTextString(m) }
func (*JobKillReq) ProtoMessage()    {}
func (*JobKillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{3}
}

func (m *JobKillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobKillReq.Unmarshal(m, b)
}
func (m *JobKillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobKillReq.Marshal(b, m, deterministic)
}
func (m *JobKillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobKillReq.Merge(m, src)
}
func (m *JobKillReq) XXX_Size() int {
	return xxx_messageInfo_JobKillReq.Size(m)
}
func (m *JobKillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JobKillReq.DiscardUnknown(m)
}

var xxx_messageInfo_JobKillReq proto.InternalMessageInfo

func (m *JobKillReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type JobKill struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobKill) Reset()         { *m = JobKill{} }
func (m *JobKill) String() string { return proto.CompactTextString(m) }
func (*JobKill) ProtoMessage()    {}
func (*JobKill) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{4}
}

func (m *JobKill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobKill.Unmarshal(m, b)
}
func (m *JobKill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobKill.Marshal(b, m, deterministic)
}
func (m *JobKill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobKill.Merge(m, src)
}
func (m *JobKill) XXX_Size() int {
	return xxx_messageInfo_JobKill.Size(m)
}
func (m *JobKill) XXX_DiscardUnknown() {
	xxx_messageInfo_JobKill.DiscardUnknown(m)
}

var xxx_messageInfo_JobKill proto.InternalMessageInfo

func (m *JobKill) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *JobKill) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *JobKill) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Jobs struct {
	Active               []*Job   `protobuf:"bytes,1,rep,name=Active,proto3" json:"Active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jobs) Reset()         { *m = Jobs{} }
func (m *Jobs) String() string { return proto.CompactTextString(m) }
func (*Jobs) ProtoMessage()    {}
func (*Jobs) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{5}
}

func (m *Jobs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jobs.Unmarshal(m, b)
}
func (m *Jobs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jobs.Marshal(b, m, deterministic)
}
func (m *Jobs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jobs.Merge(m, src)
}
func (m *Jobs) XXX_Size() int {
	return xxx_messageInfo_Jobs.Size(m)
}
func (m *Jobs) XXX_DiscardUnknown() {
	xxx_messageInfo_Jobs.DiscardUnknown(m)
}

var xxx_messageInfo_Jobs proto.InternalMessageInfo

func (m *Jobs) GetActive() []*Job {
	if m != nil {
		return m.Active
	}
	return nil
}

type MTLSReq struct {
	Server               string   `protobuf:"bytes,1,opt,name=Server,proto3" json:"Server,omitempty"`
	LPort                int32    `protobuf:"varint,2,opt,name=LPort,proto3" json:"LPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MTLSReq) Reset()         { *m = MTLSReq{} }
func (m *MTLSReq) String() string { return proto.CompactTextString(m) }
func (*MTLSReq) ProtoMessage()    {}
func (*MTLSReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{6}
}

func (m *MTLSReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MTLSReq.Unmarshal(m, b)
}
func (m *MTLSReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MTLSReq.Marshal(b, m, deterministic)
}
func (m *MTLSReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MTLSReq.Merge(m, src)
}
func (m *MTLSReq) XXX_Size() int {
	return xxx_messageInfo_MTLSReq.Size(m)
}
func (m *MTLSReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MTLSReq.DiscardUnknown(m)
}

var xxx_messageInfo_MTLSReq proto.InternalMessageInfo

func (m *MTLSReq) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *MTLSReq) GetLPort() int32 {
	if m != nil {
		return m.LPort
	}
	return 0
}

type MTLS struct {
	JobID                int32    `protobuf:"varint,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MTLS) Reset()         { *m = MTLS{} }
func (m *MTLS) String() string { return proto.CompactTextString(m) }
func (*MTLS) ProtoMessage()    {}
func (*MTLS) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{7}
}

func (m *MTLS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MTLS.Unmarshal(m, b)
}
func (m *MTLS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MTLS.Marshal(b, m, deterministic)
}
func (m *MTLS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MTLS.Merge(m, src)
}
func (m *MTLS) XXX_Size() int {
	return xxx_messageInfo_MTLS.Size(m)
}
func (m *MTLS) XXX_DiscardUnknown() {
	xxx_messageInfo_MTLS.DiscardUnknown(m)
}

var xxx_messageInfo_MTLS proto.InternalMessageInfo

func (m *MTLS) GetJobID() int32 {
	if m != nil {
		return m.JobID
	}
	return 0
}

type TCPReq struct {
	Server               string   `protobuf:"bytes,1,opt,name=Server,proto3" json:"Server,omitempty"`
	LPort                int32    `protobuf:"varint,2,opt,name=LPort,proto3" json:"LPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TCPReq) Reset()         { *m = TCPReq{} }
func (m *TCPReq) String() string { return proto.CompactTextString(m) }
func (*TCPReq) ProtoMessage()    {}
func (*TCPReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{8}
}

func (m *TCPReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TCPReq.Unmarshal(m, b)
}
func (m *TCPReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TCPReq.Marshal(b, m, deterministic)
}
func (m *TCPReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TCPReq.Merge(m, src)
}
func (m *TCPReq) XXX_Size() int {
	return xxx_messageInfo_TCPReq.Size(m)
}
func (m *TCPReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TCPReq.DiscardUnknown(m)
}

var xxx_messageInfo_TCPReq proto.InternalMessageInfo

func (m *TCPReq) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *TCPReq) GetLPort() int32 {
	if m != nil {
		return m.LPort
	}
	return 0
}

type TCP struct {
	JobID                int32    `protobuf:"varint,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TCP) Reset()         { *m = TCP{} }
func (m *TCP) String() string { return proto.CompactTextString(m) }
func (*TCP) ProtoMessage()    {}
func (*TCP) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{9}
}

func (m *TCP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TCP.Unmarshal(m, b)
}
func (m *TCP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TCP.Marshal(b, m, deterministic)
}
func (m *TCP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TCP.Merge(m, src)
}
func (m *TCP) XXX_Size() int {
	return xxx_messageInfo_TCP.Size(m)
}
func (m *TCP) XXX_DiscardUnknown() {
	xxx_messageInfo_TCP.DiscardUnknown(m)
}

var xxx_messageInfo_TCP proto.InternalMessageInfo

func (m *TCP) GetJobID() int32 {
	if m != nil {
		return m.JobID
	}
	return 0
}

type DNSReq struct {
	Domains              []string `protobuf:"bytes,1,rep,name=Domains,proto3" json:"Domains,omitempty"`
	Canaries             bool     `protobuf:"varint,2,opt,name=Canaries,proto3" json:"Canaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNSReq) Reset()         { *m = DNSReq{} }
func (m *DNSReq) String() string { return proto.CompactTextString(m) }
func (*DNSReq) ProtoMessage()    {}
func (*DNSReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{10}
}

func (m *DNSReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNSReq.Unmarshal(m, b)
}
func (m *DNSReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNSReq.Marshal(b, m, deterministic)
}
func (m *DNSReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSReq.Merge(m, src)
}
func (m *DNSReq) XXX_Size() int {
	return xxx_messageInfo_DNSReq.Size(m)
}
func (m *DNSReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSReq.DiscardUnknown(m)
}

var xxx_messageInfo_DNSReq proto.InternalMessageInfo

func (m *DNSReq) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *DNSReq) GetCanaries() bool {
	if m != nil {
		return m.Canaries
	}
	return false
}

type DNS struct {
	JobID                int32    `protobuf:"varint,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNS) Reset()         { *m = DNS{} }
func (m *DNS) String() string { return proto.CompactTextString(m) }
func (*DNS) ProtoMessage()    {}
func (*DNS) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{11}
}

func (m *DNS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNS.Unmarshal(m, b)
}
func (m *DNS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNS.Marshal(b, m, deterministic)
}
func (m *DNS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNS.Merge(m, src)
}
func (m *DNS) XXX_Size() int {
	return xxx_messageInfo_DNS.Size(m)
}
func (m *DNS) XXX_DiscardUnknown() {
	xxx_messageInfo_DNS.DiscardUnknown(m)
}

var xxx_messageInfo_DNS proto.InternalMessageInfo

func (m *DNS) GetJobID() int32 {
	if m != nil {
		return m.JobID
	}
	return 0
}

type HTTPReq struct {
	Domain               string   `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Iface                string   `protobuf:"bytes,2,opt,name=Iface,proto3" json:"Iface,omitempty"`
	LPort                int32    `protobuf:"varint,3,opt,name=LPort,proto3" json:"LPort,omitempty"`
	Secure               bool     `protobuf:"varint,4,opt,name=Secure,proto3" json:"Secure,omitempty"`
	Website              string   `protobuf:"bytes,5,opt,name=Website,proto3" json:"Website,omitempty"`
	Cert                 []byte   `protobuf:"bytes,6,opt,name=Cert,proto3" json:"Cert,omitempty"`
	Key                  []byte   `protobuf:"bytes,7,opt,name=Key,proto3" json:"Key,omitempty"`
	ACME                 bool     `protobuf:"varint,8,opt,name=ACME,proto3" json:"ACME,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPReq) Reset()         { *m = HTTPReq{} }
func (m *HTTPReq) String() string { return proto.CompactTextString(m) }
func (*HTTPReq) ProtoMessage()    {}
func (*HTTPReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{12}
}

func (m *HTTPReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPReq.Unmarshal(m, b)
}
func (m *HTTPReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPReq.Marshal(b, m, deterministic)
}
func (m *HTTPReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPReq.Merge(m, src)
}
func (m *HTTPReq) XXX_Size() int {
	return xxx_messageInfo_HTTPReq.Size(m)
}
func (m *HTTPReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPReq.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPReq proto.InternalMessageInfo

func (m *HTTPReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *HTTPReq) GetIface() string {
	if m != nil {
		return m.Iface
	}
	return ""
}

func (m *HTTPReq) GetLPort() int32 {
	if m != nil {
		return m.LPort
	}
	return 0
}

func (m *HTTPReq) GetSecure() bool {
	if m != nil {
		return m.Secure
	}
	return false
}

func (m *HTTPReq) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *HTTPReq) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *HTTPReq) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *HTTPReq) GetACME() bool {
	if m != nil {
		return m.ACME
	}
	return false
}

type HTTP struct {
	JobID                int32    `protobuf:"varint,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTP) Reset()         { *m = HTTP{} }
func (m *HTTP) String() string { return proto.CompactTextString(m) }
func (*HTTP) ProtoMessage()    {}
func (*HTTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{13}
}

func (m *HTTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTP.Unmarshal(m, b)
}
func (m *HTTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTP.Marshal(b, m, deterministic)
}
func (m *HTTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTP.Merge(m, src)
}
func (m *HTTP) XXX_Size() int {
	return xxx_messageInfo_HTTP.Size(m)
}
func (m *HTTP) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTP.DiscardUnknown(m)
}

var xxx_messageInfo_HTTP proto.InternalMessageInfo

func (m *HTTP) GetJobID() int32 {
	if m != nil {
		return m.JobID
	}
	return 0
}

// Server-side proxy, used for proxying tools like nmap
type ProxyReq struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	LHost                string   `protobuf:"bytes,2,opt,name=LHost,proto3" json:"LHost,omitempty"`
	LPort                int32    `protobuf:"varint,3,opt,name=LPort,proto3" json:"LPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyReq) Reset()         { *m = ProxyReq{} }
func (m *ProxyReq) String() string { return proto.CompactTextString(m) }
func (*ProxyReq) ProtoMessage()    {}
func (*ProxyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{14}
}

func (m *ProxyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyReq.Unmarshal(m, b)
}
func (m *ProxyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyReq.Marshal(b, m, deterministic)
}
func (m *ProxyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyReq.Merge(m, src)
}
func (m *ProxyReq) XXX_Size() int {
	return xxx_messageInfo_ProxyReq.Size(m)
}
func (m *ProxyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyReq proto.InternalMessageInfo

func (m *ProxyReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProxyReq) GetLHost() string {
	if m != nil {
		return m.LHost
	}
	return ""
}

func (m *ProxyReq) GetLPort() int32 {
	if m != nil {
		return m.LPort
	}
	return 0
}

type Proxy struct {
	JobID                int32    `protobuf:"varint,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proxy) Reset()         { *m = Proxy{} }
func (m *Proxy) String() string { return proto.CompactTextString(m) }
func (*Proxy) ProtoMessage()    {}
func (*Proxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{15}
}

func (m *Proxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proxy.Unmarshal(m, b)
}
func (m *Proxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proxy.Marshal(b, m, deterministic)
}
func (m *Proxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proxy.Merge(m, src)
}
func (m *Proxy) XXX_Size() int {
	return xxx_messageInfo_Proxy.Size(m)
}
func (m *Proxy) XXX_DiscardUnknown() {
	xxx_messageInfo_Proxy.DiscardUnknown(m)
}

var xxx_messageInfo_Proxy proto.InternalMessageInfo

func (m *Proxy) GetJobID() int32 {
	if m != nil {
		return m.JobID
	}
	return 0
}

type ScanReq struct {
	Args                 []string `protobuf:"bytes,1,rep,name=Args,proto3" json:"Args,omitempty"`
	Scanner              string   `protobuf:"bytes,2,opt,name=Scanner,proto3" json:"Scanner,omitempty"`
	WorkspaceID          string   `protobuf:"bytes,3,opt,name=WorkspaceID,proto3" json:"WorkspaceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanReq) Reset()         { *m = ScanReq{} }
func (m *ScanReq) String() string { return proto.CompactTextString(m) }
func (*ScanReq) ProtoMessage()    {}
func (*ScanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{16}
}

func (m *ScanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanReq.Unmarshal(m, b)
}
func (m *ScanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanReq.Marshal(b, m, deterministic)
}
func (m *ScanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanReq.Merge(m, src)
}
func (m *ScanReq) XXX_Size() int {
	return xxx_messageInfo_ScanReq.Size(m)
}
func (m *ScanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanReq.DiscardUnknown(m)
}

var xxx_messageInfo_ScanReq proto.InternalMessageInfo

func (m *ScanReq) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ScanReq) GetScanner() string {
	if m != nil {
		return m.Scanner
	}
	return ""
}

func (m *ScanReq) GetWorkspaceID() string {
	if m != nil {
		return m.WorkspaceID
	}
	return ""
}

type Scan struct {
	ScanID               int32    `protobuf:"varint,1,opt,name=ScanID,proto3" json:"ScanID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scan) Reset()         { *m = Scan{} }
func (m *Scan) String() string { return proto.CompactTextString(m) }
func (*Scan) ProtoMessage()    {}
func (*Scan) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{17}
}

func (m *Scan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scan.Unmarshal(m, b)
}
func (m *Scan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scan.Marshal(b, m, deterministic)
}
func (m *Scan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scan.Merge(m, src)
}
func (m *Scan) XXX_Size() int {
	return xxx_messageInfo_Scan.Size(m)
}
func (m *Scan) XXX_DiscardUnknown() {
	xxx_messageInfo_Scan.DiscardUnknown(m)
}

var xxx_messageInfo_Scan proto.InternalMessageInfo

func (m *Scan) GetScanID() int32 {
	if m != nil {
		return m.ScanID
	}
	return 0
}

// This Ghost data structure is used for actively connected ghosts.
// GhostBuild is a backup of an already built Ghost.
type Ghost struct {
	ID            uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Hostname      string `protobuf:"bytes,3,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Username      string `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	UID           string `protobuf:"bytes,5,opt,name=UID,proto3" json:"UID,omitempty"`
	GID           string `protobuf:"bytes,6,opt,name=GID,proto3" json:"GID,omitempty"`
	OS            string `protobuf:"bytes,7,opt,name=OS,proto3" json:"OS,omitempty"`
	Arch          string `protobuf:"bytes,8,opt,name=Arch,proto3" json:"Arch,omitempty"`
	Transport     string `protobuf:"bytes,9,opt,name=Transport,proto3" json:"Transport,omitempty"`
	RemoteAddress string `protobuf:"bytes,10,opt,name=RemoteAddress,proto3" json:"RemoteAddress,omitempty"`
	PID           int32  `protobuf:"varint,11,opt,name=PID,proto3" json:"PID,omitempty"`
	Filename      string `protobuf:"bytes,12,opt,name=Filename,proto3" json:"Filename,omitempty"`
	LastCheckin   string `protobuf:"bytes,13,opt,name=LastCheckin,proto3" json:"LastCheckin,omitempty"`
	ActiveC2      string `protobuf:"bytes,14,opt,name=ActiveC2,proto3" json:"ActiveC2,omitempty"`
	Version       string `protobuf:"bytes,15,opt,name=Version,proto3" json:"Version,omitempty"`
	// Added
	WorkspaceID          uint32   `protobuf:"varint,18,opt,name=WorkspaceID,proto3" json:"WorkspaceID,omitempty"`
	HostID               uint32   `protobuf:"varint,17,opt,name=HostID,proto3" json:"HostID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ghost) Reset()         { *m = Ghost{} }
func (m *Ghost) String() string { return proto.CompactTextString(m) }
func (*Ghost) ProtoMessage()    {}
func (*Ghost) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{18}
}

func (m *Ghost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ghost.Unmarshal(m, b)
}
func (m *Ghost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ghost.Marshal(b, m, deterministic)
}
func (m *Ghost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ghost.Merge(m, src)
}
func (m *Ghost) XXX_Size() int {
	return xxx_messageInfo_Ghost.Size(m)
}
func (m *Ghost) XXX_DiscardUnknown() {
	xxx_messageInfo_Ghost.DiscardUnknown(m)
}

var xxx_messageInfo_Ghost proto.InternalMessageInfo

func (m *Ghost) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Ghost) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ghost) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Ghost) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Ghost) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *Ghost) GetGID() string {
	if m != nil {
		return m.GID
	}
	return ""
}

func (m *Ghost) GetOS() string {
	if m != nil {
		return m.OS
	}
	return ""
}

func (m *Ghost) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Ghost) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

func (m *Ghost) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

func (m *Ghost) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *Ghost) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Ghost) GetLastCheckin() string {
	if m != nil {
		return m.LastCheckin
	}
	return ""
}

func (m *Ghost) GetActiveC2() string {
	if m != nil {
		return m.ActiveC2
	}
	return ""
}

func (m *Ghost) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Ghost) GetWorkspaceID() uint32 {
	if m != nil {
		return m.WorkspaceID
	}
	return 0
}

func (m *Ghost) GetHostID() uint32 {
	if m != nil {
		return m.HostID
	}
	return 0
}

type GhostC2 struct {
	Priority             uint32   `protobuf:"varint,1,opt,name=Priority,proto3" json:"Priority,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Options              string   `protobuf:"bytes,3,opt,name=Options,proto3" json:"Options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GhostC2) Reset()         { *m = GhostC2{} }
func (m *GhostC2) String() string { return proto.CompactTextString(m) }
func (*GhostC2) ProtoMessage()    {}
func (*GhostC2) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{19}
}

func (m *GhostC2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GhostC2.Unmarshal(m, b)
}
func (m *GhostC2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GhostC2.Marshal(b, m, deterministic)
}
func (m *GhostC2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GhostC2.Merge(m, src)
}
func (m *GhostC2) XXX_Size() int {
	return xxx_messageInfo_GhostC2.Size(m)
}
func (m *GhostC2) XXX_DiscardUnknown() {
	xxx_messageInfo_GhostC2.DiscardUnknown(m)
}

var xxx_messageInfo_GhostC2 proto.InternalMessageInfo

func (m *GhostC2) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *GhostC2) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *GhostC2) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

// When an implant is compiled and needs to reach back to the server via a pivot,
// this message is used to tell which implant to reach first. Then, by giving it
// the ultimate server address, the proxy will redirect to it.
type GhostProxy struct {
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Options              string   `protobuf:"bytes,3,opt,name=Options,proto3" json:"Options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GhostProxy) Reset()         { *m = GhostProxy{} }
func (m *GhostProxy) String() string { return proto.CompactTextString(m) }
func (*GhostProxy) ProtoMessage()    {}
func (*GhostProxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{20}
}

func (m *GhostProxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GhostProxy.Unmarshal(m, b)
}
func (m *GhostProxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GhostProxy.Marshal(b, m, deterministic)
}
func (m *GhostProxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GhostProxy.Merge(m, src)
}
func (m *GhostProxy) XXX_Size() int {
	return xxx_messageInfo_GhostProxy.Size(m)
}
func (m *GhostProxy) XXX_DiscardUnknown() {
	xxx_messageInfo_GhostProxy.DiscardUnknown(m)
}

var xxx_messageInfo_GhostProxy proto.InternalMessageInfo

func (m *GhostProxy) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *GhostProxy) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

type GhostConfig struct {
	GOOS                string `protobuf:"bytes,1,opt,name=GOOS,proto3" json:"GOOS,omitempty"`
	GOARCH              string `protobuf:"bytes,2,opt,name=GOARCH,proto3" json:"GOARCH,omitempty"`
	Name                string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	CACert              string `protobuf:"bytes,4,opt,name=CACert,proto3" json:"CACert,omitempty"`
	Cert                string `protobuf:"bytes,5,opt,name=Cert,proto3" json:"Cert,omitempty"`
	Key                 string `protobuf:"bytes,6,opt,name=Key,proto3" json:"Key,omitempty"`
	Debug               bool   `protobuf:"varint,7,opt,name=Debug,proto3" json:"Debug,omitempty"`
	ObfuscateSymbols    bool   `protobuf:"varint,30,opt,name=ObfuscateSymbols,proto3" json:"ObfuscateSymbols,omitempty"`
	ReconnectInterval   uint32 `protobuf:"varint,8,opt,name=ReconnectInterval,proto3" json:"ReconnectInterval,omitempty"`
	MaxConnectionErrors uint32 `protobuf:"varint,9,opt,name=MaxConnectionErrors,proto3" json:"MaxConnectionErrors,omitempty"`
	// C2
	C2                []*GhostC2               `protobuf:"bytes,10,rep,name=C2,proto3" json:"C2,omitempty"`
	CanaryDomains     []string                 `protobuf:"bytes,11,rep,name=CanaryDomains,proto3" json:"CanaryDomains,omitempty"`
	LimitDomainJoined bool                     `protobuf:"varint,20,opt,name=LimitDomainJoined,proto3" json:"LimitDomainJoined,omitempty"`
	LimitDatetime     string                   `protobuf:"bytes,21,opt,name=LimitDatetime,proto3" json:"LimitDatetime,omitempty"`
	LimitHostname     string                   `protobuf:"bytes,22,opt,name=LimitHostname,proto3" json:"LimitHostname,omitempty"`
	LimitUsername     string                   `protobuf:"bytes,23,opt,name=LimitUsername,proto3" json:"LimitUsername,omitempty"`
	Format            GhostConfig_OutputFormat `protobuf:"varint,25,opt,name=Format,proto3,enum=clientpb.GhostConfig_OutputFormat" json:"Format,omitempty"`
	IsSharedLib       bool                     `protobuf:"varint,26,opt,name=IsSharedLib,proto3" json:"IsSharedLib,omitempty"`
	Filename          string                   `protobuf:"bytes,27,opt,name=Filename,proto3" json:"Filename,omitempty"`
	// Added
	WorkspaceID          uint32        `protobuf:"varint,28,opt,name=WorkspaceID,proto3" json:"WorkspaceID,omitempty"`
	Proxy                []*GhostProxy `protobuf:"bytes,29,rep,name=Proxy,proto3" json:"Proxy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GhostConfig) Reset()         { *m = GhostConfig{} }
func (m *GhostConfig) String() string { return proto.CompactTextString(m) }
func (*GhostConfig) ProtoMessage()    {}
func (*GhostConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{21}
}

func (m *GhostConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GhostConfig.Unmarshal(m, b)
}
func (m *GhostConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GhostConfig.Marshal(b, m, deterministic)
}
func (m *GhostConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GhostConfig.Merge(m, src)
}
func (m *GhostConfig) XXX_Size() int {
	return xxx_messageInfo_GhostConfig.Size(m)
}
func (m *GhostConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GhostConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GhostConfig proto.InternalMessageInfo

func (m *GhostConfig) GetGOOS() string {
	if m != nil {
		return m.GOOS
	}
	return ""
}

func (m *GhostConfig) GetGOARCH() string {
	if m != nil {
		return m.GOARCH
	}
	return ""
}

func (m *GhostConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GhostConfig) GetCACert() string {
	if m != nil {
		return m.CACert
	}
	return ""
}

func (m *GhostConfig) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *GhostConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GhostConfig) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *GhostConfig) GetObfuscateSymbols() bool {
	if m != nil {
		return m.ObfuscateSymbols
	}
	return false
}

func (m *GhostConfig) GetReconnectInterval() uint32 {
	if m != nil {
		return m.ReconnectInterval
	}
	return 0
}

func (m *GhostConfig) GetMaxConnectionErrors() uint32 {
	if m != nil {
		return m.MaxConnectionErrors
	}
	return 0
}

func (m *GhostConfig) GetC2() []*GhostC2 {
	if m != nil {
		return m.C2
	}
	return nil
}

func (m *GhostConfig) GetCanaryDomains() []string {
	if m != nil {
		return m.CanaryDomains
	}
	return nil
}

func (m *GhostConfig) GetLimitDomainJoined() bool {
	if m != nil {
		return m.LimitDomainJoined
	}
	return false
}

func (m *GhostConfig) GetLimitDatetime() string {
	if m != nil {
		return m.LimitDatetime
	}
	return ""
}

func (m *GhostConfig) GetLimitHostname() string {
	if m != nil {
		return m.LimitHostname
	}
	return ""
}

func (m *GhostConfig) GetLimitUsername() string {
	if m != nil {
		return m.LimitUsername
	}
	return ""
}

func (m *GhostConfig) GetFormat() GhostConfig_OutputFormat {
	if m != nil {
		return m.Format
	}
	return GhostConfig_SHARED_LIB
}

func (m *GhostConfig) GetIsSharedLib() bool {
	if m != nil {
		return m.IsSharedLib
	}
	return false
}

func (m *GhostConfig) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *GhostConfig) GetWorkspaceID() uint32 {
	if m != nil {
		return m.WorkspaceID
	}
	return 0
}

func (m *GhostConfig) GetProxy() []*GhostProxy {
	if m != nil {
		return m.Proxy
	}
	return nil
}

// Configs of previously built ghosts
type GhostBuilds struct {
	Configs              map[string]*GhostConfig `protobuf:"bytes,1,rep,name=Configs,proto3" json:"Configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GhostBuilds) Reset()         { *m = GhostBuilds{} }
func (m *GhostBuilds) String() string { return proto.CompactTextString(m) }
func (*GhostBuilds) ProtoMessage()    {}
func (*GhostBuilds) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{22}
}

func (m *GhostBuilds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GhostBuilds.Unmarshal(m, b)
}
func (m *GhostBuilds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GhostBuilds.Marshal(b, m, deterministic)
}
func (m *GhostBuilds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GhostBuilds.Merge(m, src)
}
func (m *GhostBuilds) XXX_Size() int {
	return xxx_messageInfo_GhostBuilds.Size(m)
}
func (m *GhostBuilds) XXX_DiscardUnknown() {
	xxx_messageInfo_GhostBuilds.DiscardUnknown(m)
}

var xxx_messageInfo_GhostBuilds proto.InternalMessageInfo

func (m *GhostBuilds) GetConfigs() map[string]*GhostConfig {
	if m != nil {
		return m.Configs
	}
	return nil
}

// DNSCanary - Single canary and metadata
type DNSCanary struct {
	GhostName            string   `protobuf:"bytes,1,opt,name=GhostName,proto3" json:"GhostName,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Triggered            bool     `protobuf:"varint,3,opt,name=Triggered,proto3" json:"Triggered,omitempty"`
	FirstTriggered       string   `protobuf:"bytes,4,opt,name=FirstTriggered,proto3" json:"FirstTriggered,omitempty"`
	LatestTrigger        string   `protobuf:"bytes,5,opt,name=LatestTrigger,proto3" json:"LatestTrigger,omitempty"`
	Count                uint32   `protobuf:"varint,6,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNSCanary) Reset()         { *m = DNSCanary{} }
func (m *DNSCanary) String() string { return proto.CompactTextString(m) }
func (*DNSCanary) ProtoMessage()    {}
func (*DNSCanary) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{23}
}

func (m *DNSCanary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNSCanary.Unmarshal(m, b)
}
func (m *DNSCanary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNSCanary.Marshal(b, m, deterministic)
}
func (m *DNSCanary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSCanary.Merge(m, src)
}
func (m *DNSCanary) XXX_Size() int {
	return xxx_messageInfo_DNSCanary.Size(m)
}
func (m *DNSCanary) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSCanary.DiscardUnknown(m)
}

var xxx_messageInfo_DNSCanary proto.InternalMessageInfo

func (m *DNSCanary) GetGhostName() string {
	if m != nil {
		return m.GhostName
	}
	return ""
}

func (m *DNSCanary) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DNSCanary) GetTriggered() bool {
	if m != nil {
		return m.Triggered
	}
	return false
}

func (m *DNSCanary) GetFirstTriggered() string {
	if m != nil {
		return m.FirstTriggered
	}
	return ""
}

func (m *DNSCanary) GetLatestTrigger() string {
	if m != nil {
		return m.LatestTrigger
	}
	return ""
}

func (m *DNSCanary) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Canaries struct {
	Canaries             []*DNSCanary `protobuf:"bytes,1,rep,name=Canaries,proto3" json:"Canaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Canaries) Reset()         { *m = Canaries{} }
func (m *Canaries) String() string { return proto.CompactTextString(m) }
func (*Canaries) ProtoMessage()    {}
func (*Canaries) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{24}
}

func (m *Canaries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Canaries.Unmarshal(m, b)
}
func (m *Canaries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Canaries.Marshal(b, m, deterministic)
}
func (m *Canaries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Canaries.Merge(m, src)
}
func (m *Canaries) XXX_Size() int {
	return xxx_messageInfo_Canaries.Size(m)
}
func (m *Canaries) XXX_DiscardUnknown() {
	xxx_messageInfo_Canaries.DiscardUnknown(m)
}

var xxx_messageInfo_Canaries proto.InternalMessageInfo

func (m *Canaries) GetCanaries() []*DNSCanary {
	if m != nil {
		return m.Canaries
	}
	return nil
}

type Profile struct {
	Name                 string       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Config               *GhostConfig `protobuf:"bytes,2,opt,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{25}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetConfig() *GhostConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type Profiles struct {
	List                 []*Profile `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Profiles) Reset()         { *m = Profiles{} }
func (m *Profiles) String() string { return proto.CompactTextString(m) }
func (*Profiles) ProtoMessage()    {}
func (*Profiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{26}
}

func (m *Profiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profiles.Unmarshal(m, b)
}
func (m *Profiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profiles.Marshal(b, m, deterministic)
}
func (m *Profiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profiles.Merge(m, src)
}
func (m *Profiles) XXX_Size() int {
	return xxx_messageInfo_Profiles.Size(m)
}
func (m *Profiles) XXX_DiscardUnknown() {
	xxx_messageInfo_Profiles.DiscardUnknown(m)
}

var xxx_messageInfo_Profiles proto.InternalMessageInfo

func (m *Profiles) GetList() []*Profile {
	if m != nil {
		return m.List
	}
	return nil
}

type Regenerate struct {
	GhostName            string   `protobuf:"bytes,1,opt,name=GhostName,proto3" json:"GhostName,omitempty"`
	File                 *File    `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Regenerate) Reset()         { *m = Regenerate{} }
func (m *Regenerate) String() string { return proto.CompactTextString(m) }
func (*Regenerate) ProtoMessage()    {}
func (*Regenerate) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{27}
}

func (m *Regenerate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Regenerate.Unmarshal(m, b)
}
func (m *Regenerate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Regenerate.Marshal(b, m, deterministic)
}
func (m *Regenerate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Regenerate.Merge(m, src)
}
func (m *Regenerate) XXX_Size() int {
	return xxx_messageInfo_Regenerate.Size(m)
}
func (m *Regenerate) XXX_DiscardUnknown() {
	xxx_messageInfo_Regenerate.DiscardUnknown(m)
}

var xxx_messageInfo_Regenerate proto.InternalMessageInfo

func (m *Regenerate) GetGhostName() string {
	if m != nil {
		return m.GhostName
	}
	return ""
}

func (m *Regenerate) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type Sessions struct {
	Ghosts               []*Ghost `protobuf:"bytes,1,rep,name=Ghosts,proto3" json:"Ghosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sessions) Reset()         { *m = Sessions{} }
func (m *Sessions) String() string { return proto.CompactTextString(m) }
func (*Sessions) ProtoMessage()    {}
func (*Sessions) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{28}
}

func (m *Sessions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sessions.Unmarshal(m, b)
}
func (m *Sessions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sessions.Marshal(b, m, deterministic)
}
func (m *Sessions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sessions.Merge(m, src)
}
func (m *Sessions) XXX_Size() int {
	return xxx_messageInfo_Sessions.Size(m)
}
func (m *Sessions) XXX_DiscardUnknown() {
	xxx_messageInfo_Sessions.DiscardUnknown(m)
}

var xxx_messageInfo_Sessions proto.InternalMessageInfo

func (m *Sessions) GetGhosts() []*Ghost {
	if m != nil {
		return m.Ghosts
	}
	return nil
}

type GenerateReq struct {
	Config               *GhostConfig `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenerateReq) Reset()         { *m = GenerateReq{} }
func (m *GenerateReq) String() string { return proto.CompactTextString(m) }
func (*GenerateReq) ProtoMessage()    {}
func (*GenerateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{29}
}

func (m *GenerateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateReq.Unmarshal(m, b)
}
func (m *GenerateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateReq.Marshal(b, m, deterministic)
}
func (m *GenerateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateReq.Merge(m, src)
}
func (m *GenerateReq) XXX_Size() int {
	return xxx_messageInfo_GenerateReq.Size(m)
}
func (m *GenerateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateReq proto.InternalMessageInfo

func (m *GenerateReq) GetConfig() *GhostConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type Generate struct {
	File                 *File    `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Generate) Reset()         { *m = Generate{} }
func (m *Generate) String() string { return proto.CompactTextString(m) }
func (*Generate) ProtoMessage()    {}
func (*Generate) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{30}
}

func (m *Generate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Generate.Unmarshal(m, b)
}
func (m *Generate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Generate.Marshal(b, m, deterministic)
}
func (m *Generate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Generate.Merge(m, src)
}
func (m *Generate) XXX_Size() int {
	return xxx_messageInfo_Generate.Size(m)
}
func (m *Generate) XXX_DiscardUnknown() {
	xxx_messageInfo_Generate.DiscardUnknown(m)
}

var xxx_messageInfo_Generate proto.InternalMessageInfo

func (m *Generate) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type MSFReq struct {
	Payload              string   `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	LHost                string   `protobuf:"bytes,2,opt,name=LHost,proto3" json:"LHost,omitempty"`
	LPort                int32    `protobuf:"varint,3,opt,name=LPort,proto3" json:"LPort,omitempty"`
	Encoder              string   `protobuf:"bytes,4,opt,name=Encoder,proto3" json:"Encoder,omitempty"`
	Iterations           int32    `protobuf:"varint,5,opt,name=Iterations,proto3" json:"Iterations,omitempty"`
	GhostID              uint32   `protobuf:"varint,9,opt,name=GhostID,proto3" json:"GhostID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MSFReq) Reset()         { *m = MSFReq{} }
func (m *MSFReq) String() string { return proto.CompactTextString(m) }
func (*MSFReq) ProtoMessage()    {}
func (*MSFReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{31}
}

func (m *MSFReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MSFReq.Unmarshal(m, b)
}
func (m *MSFReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MSFReq.Marshal(b, m, deterministic)
}
func (m *MSFReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MSFReq.Merge(m, src)
}
func (m *MSFReq) XXX_Size() int {
	return xxx_messageInfo_MSFReq.Size(m)
}
func (m *MSFReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MSFReq.DiscardUnknown(m)
}

var xxx_messageInfo_MSFReq proto.InternalMessageInfo

func (m *MSFReq) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *MSFReq) GetLHost() string {
	if m != nil {
		return m.LHost
	}
	return ""
}

func (m *MSFReq) GetLPort() int32 {
	if m != nil {
		return m.LPort
	}
	return 0
}

func (m *MSFReq) GetEncoder() string {
	if m != nil {
		return m.Encoder
	}
	return ""
}

func (m *MSFReq) GetIterations() int32 {
	if m != nil {
		return m.Iterations
	}
	return 0
}

func (m *MSFReq) GetGhostID() uint32 {
	if m != nil {
		return m.GhostID
	}
	return 0
}

type MSFInjectReq struct {
	Payload              string   `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	LHost                string   `protobuf:"bytes,2,opt,name=LHost,proto3" json:"LHost,omitempty"`
	LPort                int32    `protobuf:"varint,3,opt,name=LPort,proto3" json:"LPort,omitempty"`
	Encoder              string   `protobuf:"bytes,4,opt,name=Encoder,proto3" json:"Encoder,omitempty"`
	Iterations           int32    `protobuf:"varint,5,opt,name=Iterations,proto3" json:"Iterations,omitempty"`
	PID                  int32    `protobuf:"varint,8,opt,name=PID,proto3" json:"PID,omitempty"`
	GhostID              uint32   `protobuf:"varint,9,opt,name=GhostID,proto3" json:"GhostID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MSFInjectReq) Reset()         { *m = MSFInjectReq{} }
func (m *MSFInjectReq) String() string { return proto.CompactTextString(m) }
func (*MSFInjectReq) ProtoMessage()    {}
func (*MSFInjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{32}
}

func (m *MSFInjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MSFInjectReq.Unmarshal(m, b)
}
func (m *MSFInjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MSFInjectReq.Marshal(b, m, deterministic)
}
func (m *MSFInjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MSFInjectReq.Merge(m, src)
}
func (m *MSFInjectReq) XXX_Size() int {
	return xxx_messageInfo_MSFInjectReq.Size(m)
}
func (m *MSFInjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MSFInjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_MSFInjectReq proto.InternalMessageInfo

func (m *MSFInjectReq) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *MSFInjectReq) GetLHost() string {
	if m != nil {
		return m.LHost
	}
	return ""
}

func (m *MSFInjectReq) GetLPort() int32 {
	if m != nil {
		return m.LPort
	}
	return 0
}

func (m *MSFInjectReq) GetEncoder() string {
	if m != nil {
		return m.Encoder
	}
	return ""
}

func (m *MSFInjectReq) GetIterations() int32 {
	if m != nil {
		return m.Iterations
	}
	return 0
}

func (m *MSFInjectReq) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *MSFInjectReq) GetGhostID() uint32 {
	if m != nil {
		return m.GhostID
	}
	return 0
}

type TaskReq struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	RwxPages             bool     `protobuf:"varint,2,opt,name=RwxPages,proto3" json:"RwxPages,omitempty"`
	Pid                  uint32   `protobuf:"varint,3,opt,name=Pid,proto3" json:"Pid,omitempty"`
	GhostID              uint32   `protobuf:"varint,9,opt,name=GhostID,proto3" json:"GhostID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskReq) Reset()         { *m = TaskReq{} }
func (m *TaskReq) String() string { return proto.CompactTextString(m) }
func (*TaskReq) ProtoMessage()    {}
func (*TaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{33}
}

func (m *TaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskReq.Unmarshal(m, b)
}
func (m *TaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskReq.Marshal(b, m, deterministic)
}
func (m *TaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskReq.Merge(m, src)
}
func (m *TaskReq) XXX_Size() int {
	return xxx_messageInfo_TaskReq.Size(m)
}
func (m *TaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_TaskReq proto.InternalMessageInfo

func (m *TaskReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TaskReq) GetRwxPages() bool {
	if m != nil {
		return m.RwxPages
	}
	return false
}

func (m *TaskReq) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *TaskReq) GetGhostID() uint32 {
	if m != nil {
		return m.GhostID
	}
	return 0
}

type MigrateReq struct {
	Pid                  uint32       `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Config               *GhostConfig `protobuf:"bytes,2,opt,name=Config,proto3" json:"Config,omitempty"`
	GhostID              uint32       `protobuf:"varint,3,opt,name=GhostID,proto3" json:"GhostID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MigrateReq) Reset()         { *m = MigrateReq{} }
func (m *MigrateReq) String() string { return proto.CompactTextString(m) }
func (*MigrateReq) ProtoMessage()    {}
func (*MigrateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{34}
}

func (m *MigrateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateReq.Unmarshal(m, b)
}
func (m *MigrateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateReq.Marshal(b, m, deterministic)
}
func (m *MigrateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateReq.Merge(m, src)
}
func (m *MigrateReq) XXX_Size() int {
	return xxx_messageInfo_MigrateReq.Size(m)
}
func (m *MigrateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateReq.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateReq proto.InternalMessageInfo

func (m *MigrateReq) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *MigrateReq) GetConfig() *GhostConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *MigrateReq) GetGhostID() uint32 {
	if m != nil {
		return m.GhostID
	}
	return 0
}

type GetSystemReq struct {
	Config               *GhostConfig `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	HostingProcess       string       `protobuf:"bytes,2,opt,name=HostingProcess,proto3" json:"HostingProcess,omitempty"`
	GhostID              uint32       `protobuf:"varint,9,opt,name=GhostID,proto3" json:"GhostID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetSystemReq) Reset()         { *m = GetSystemReq{} }
func (m *GetSystemReq) String() string { return proto.CompactTextString(m) }
func (*GetSystemReq) ProtoMessage()    {}
func (*GetSystemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{35}
}

func (m *GetSystemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemReq.Unmarshal(m, b)
}
func (m *GetSystemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemReq.Marshal(b, m, deterministic)
}
func (m *GetSystemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemReq.Merge(m, src)
}
func (m *GetSystemReq) XXX_Size() int {
	return xxx_messageInfo_GetSystemReq.Size(m)
}
func (m *GetSystemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemReq proto.InternalMessageInfo

func (m *GetSystemReq) GetConfig() *GhostConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *GetSystemReq) GetHostingProcess() string {
	if m != nil {
		return m.HostingProcess
	}
	return ""
}

func (m *GetSystemReq) GetGhostID() uint32 {
	if m != nil {
		return m.GhostID
	}
	return 0
}

type EggConfig struct {
	Protocol             EggConfig_EggProtocol `protobuf:"varint,1,opt,name=Protocol,proto3,enum=clientpb.EggConfig_EggProtocol" json:"Protocol,omitempty"`
	Host                 string                `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Port                 uint32                `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	Arch                 string                `protobuf:"bytes,4,opt,name=Arch,proto3" json:"Arch,omitempty"`
	Format               string                `protobuf:"bytes,5,opt,name=Format,proto3" json:"Format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EggConfig) Reset()         { *m = EggConfig{} }
func (m *EggConfig) String() string { return proto.CompactTextString(m) }
func (*EggConfig) ProtoMessage()    {}
func (*EggConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{36}
}

func (m *EggConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EggConfig.Unmarshal(m, b)
}
func (m *EggConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EggConfig.Marshal(b, m, deterministic)
}
func (m *EggConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EggConfig.Merge(m, src)
}
func (m *EggConfig) XXX_Size() int {
	return xxx_messageInfo_EggConfig.Size(m)
}
func (m *EggConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EggConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EggConfig proto.InternalMessageInfo

func (m *EggConfig) GetProtocol() EggConfig_EggProtocol {
	if m != nil {
		return m.Protocol
	}
	return EggConfig_TCP
}

func (m *EggConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *EggConfig) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *EggConfig) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *EggConfig) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type EggRequest struct {
	Config               *GhostConfig `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	EConfig              *EggConfig   `protobuf:"bytes,2,opt,name=EConfig,proto3" json:"EConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EggRequest) Reset()         { *m = EggRequest{} }
func (m *EggRequest) String() string { return proto.CompactTextString(m) }
func (*EggRequest) ProtoMessage()    {}
func (*EggRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{37}
}

func (m *EggRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EggRequest.Unmarshal(m, b)
}
func (m *EggRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EggRequest.Marshal(b, m, deterministic)
}
func (m *EggRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EggRequest.Merge(m, src)
}
func (m *EggRequest) XXX_Size() int {
	return xxx_messageInfo_EggRequest.Size(m)
}
func (m *EggRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EggRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EggRequest proto.InternalMessageInfo

func (m *EggRequest) GetConfig() *GhostConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *EggRequest) GetEConfig() *EggConfig {
	if m != nil {
		return m.EConfig
	}
	return nil
}

type Egg struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=Filename,proto3" json:"Filename,omitempty"`
	JobID                int32    `protobuf:"varint,3,opt,name=JobID,proto3" json:"JobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Egg) Reset()         { *m = Egg{} }
func (m *Egg) String() string { return proto.CompactTextString(m) }
func (*Egg) ProtoMessage()    {}
func (*Egg) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{38}
}

func (m *Egg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Egg.Unmarshal(m, b)
}
func (m *Egg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Egg.Marshal(b, m, deterministic)
}
func (m *Egg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Egg.Merge(m, src)
}
func (m *Egg) XXX_Size() int {
	return xxx_messageInfo_Egg.Size(m)
}
func (m *Egg) XXX_DiscardUnknown() {
	xxx_messageInfo_Egg.DiscardUnknown(m)
}

var xxx_messageInfo_Egg proto.InternalMessageInfo

func (m *Egg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Egg) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Egg) GetJobID() int32 {
	if m != nil {
		return m.JobID
	}
	return 0
}

type SideloadReq struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	ProcName             string   `protobuf:"bytes,2,opt,name=ProcName,proto3" json:"ProcName,omitempty"`
	Args                 string   `protobuf:"bytes,3,opt,name=Args,proto3" json:"Args,omitempty"`
	EntryPoint           string   `protobuf:"bytes,4,opt,name=EntryPoint,proto3" json:"EntryPoint,omitempty"`
	GhostID              uint32   `protobuf:"varint,5,opt,name=GhostID,proto3" json:"GhostID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SideloadReq) Reset()         { *m = SideloadReq{} }
func (m *SideloadReq) String() string { return proto.CompactTextString(m) }
func (*SideloadReq) ProtoMessage()    {}
func (*SideloadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{39}
}

func (m *SideloadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SideloadReq.Unmarshal(m, b)
}
func (m *SideloadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SideloadReq.Marshal(b, m, deterministic)
}
func (m *SideloadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SideloadReq.Merge(m, src)
}
func (m *SideloadReq) XXX_Size() int {
	return xxx_messageInfo_SideloadReq.Size(m)
}
func (m *SideloadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SideloadReq.DiscardUnknown(m)
}

var xxx_messageInfo_SideloadReq proto.InternalMessageInfo

func (m *SideloadReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SideloadReq) GetProcName() string {
	if m != nil {
		return m.ProcName
	}
	return ""
}

func (m *SideloadReq) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *SideloadReq) GetEntryPoint() string {
	if m != nil {
		return m.EntryPoint
	}
	return ""
}

func (m *SideloadReq) GetGhostID() uint32 {
	if m != nil {
		return m.GhostID
	}
	return 0
}

type TunnelCreateReq struct {
	GhostID              uint32   `protobuf:"varint,1,opt,name=GhostID,proto3" json:"GhostID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TunnelCreateReq) Reset()         { *m = TunnelCreateReq{} }
func (m *TunnelCreateReq) String() string { return proto.CompactTextString(m) }
func (*TunnelCreateReq) ProtoMessage()    {}
func (*TunnelCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{40}
}

func (m *TunnelCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelCreateReq.Unmarshal(m, b)
}
func (m *TunnelCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelCreateReq.Marshal(b, m, deterministic)
}
func (m *TunnelCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelCreateReq.Merge(m, src)
}
func (m *TunnelCreateReq) XXX_Size() int {
	return xxx_messageInfo_TunnelCreateReq.Size(m)
}
func (m *TunnelCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelCreateReq proto.InternalMessageInfo

func (m *TunnelCreateReq) GetGhostID() uint32 {
	if m != nil {
		return m.GhostID
	}
	return 0
}

type TunnelCreate struct {
	GhostID              uint32   `protobuf:"varint,1,opt,name=GhostID,proto3" json:"GhostID,omitempty"`
	TunnelID             uint64   `protobuf:"varint,9,opt,name=TunnelID,proto3" json:"TunnelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TunnelCreate) Reset()         { *m = TunnelCreate{} }
func (m *TunnelCreate) String() string { return proto.CompactTextString(m) }
func (*TunnelCreate) ProtoMessage()    {}
func (*TunnelCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{41}
}

func (m *TunnelCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelCreate.Unmarshal(m, b)
}
func (m *TunnelCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelCreate.Marshal(b, m, deterministic)
}
func (m *TunnelCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelCreate.Merge(m, src)
}
func (m *TunnelCreate) XXX_Size() int {
	return xxx_messageInfo_TunnelCreate.Size(m)
}
func (m *TunnelCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelCreate.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelCreate proto.InternalMessageInfo

func (m *TunnelCreate) GetGhostID() uint32 {
	if m != nil {
		return m.GhostID
	}
	return 0
}

func (m *TunnelCreate) GetTunnelID() uint64 {
	if m != nil {
		return m.TunnelID
	}
	return 0
}

type TunnelCloseReq struct {
	TunnelID             uint64   `protobuf:"varint,9,opt,name=TunnelID,proto3" json:"TunnelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TunnelCloseReq) Reset()         { *m = TunnelCloseReq{} }
func (m *TunnelCloseReq) String() string { return proto.CompactTextString(m) }
func (*TunnelCloseReq) ProtoMessage()    {}
func (*TunnelCloseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{42}
}

func (m *TunnelCloseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelCloseReq.Unmarshal(m, b)
}
func (m *TunnelCloseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelCloseReq.Marshal(b, m, deterministic)
}
func (m *TunnelCloseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelCloseReq.Merge(m, src)
}
func (m *TunnelCloseReq) XXX_Size() int {
	return xxx_messageInfo_TunnelCloseReq.Size(m)
}
func (m *TunnelCloseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelCloseReq.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelCloseReq proto.InternalMessageInfo

func (m *TunnelCloseReq) GetTunnelID() uint64 {
	if m != nil {
		return m.TunnelID
	}
	return 0
}

type Client struct {
	ID   int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	User string `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	// Added
	WorkspaceID          uint32   `protobuf:"varint,3,opt,name=WorkspaceID,proto3" json:"WorkspaceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{43}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Client) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Client) GetWorkspaceID() uint32 {
	if m != nil {
		return m.WorkspaceID
	}
	return 0
}

type Event struct {
	EventType            string   `protobuf:"bytes,1,opt,name=EventType,proto3" json:"EventType,omitempty"`
	Ghost                *Ghost   `protobuf:"bytes,2,opt,name=Ghost,proto3" json:"Ghost,omitempty"`
	Job                  *Job     `protobuf:"bytes,3,opt,name=Job,proto3" json:"Job,omitempty"`
	Client               *Client  `protobuf:"bytes,4,opt,name=Client,proto3" json:"Client,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
	Err                  string   `protobuf:"bytes,9,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{44}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *Event) GetGhost() *Ghost {
	if m != nil {
		return m.Ghost
	}
	return nil
}

func (m *Event) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *Event) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Players struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=Players,proto3" json:"Players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Players) Reset()         { *m = Players{} }
func (m *Players) String() string { return proto.CompactTextString(m) }
func (*Players) ProtoMessage()    {}
func (*Players) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{45}
}

func (m *Players) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Players.Unmarshal(m, b)
}
func (m *Players) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Players.Marshal(b, m, deterministic)
}
func (m *Players) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Players.Merge(m, src)
}
func (m *Players) XXX_Size() int {
	return xxx_messageInfo_Players.Size(m)
}
func (m *Players) XXX_DiscardUnknown() {
	xxx_messageInfo_Players.DiscardUnknown(m)
}

var xxx_messageInfo_Players proto.InternalMessageInfo

func (m *Players) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Player struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Online               bool     `protobuf:"varint,2,opt,name=Online,proto3" json:"Online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{46}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Player) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

type WebContent struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	ContentType          string   `protobuf:"bytes,2,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	Content              []byte   `protobuf:"bytes,9,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebContent) Reset()         { *m = WebContent{} }
func (m *WebContent) String() string { return proto.CompactTextString(m) }
func (*WebContent) ProtoMessage()    {}
func (*WebContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{47}
}

func (m *WebContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebContent.Unmarshal(m, b)
}
func (m *WebContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebContent.Marshal(b, m, deterministic)
}
func (m *WebContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebContent.Merge(m, src)
}
func (m *WebContent) XXX_Size() int {
	return xxx_messageInfo_WebContent.Size(m)
}
func (m *WebContent) XXX_DiscardUnknown() {
	xxx_messageInfo_WebContent.DiscardUnknown(m)
}

var xxx_messageInfo_WebContent proto.InternalMessageInfo

func (m *WebContent) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *WebContent) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *WebContent) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *WebContent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Website struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Content              map[string]*WebContent `protobuf:"bytes,2,rep,name=Content,proto3" json:"Content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Website) Reset()         { *m = Website{} }
func (m *Website) String() string { return proto.CompactTextString(m) }
func (*Website) ProtoMessage()    {}
func (*Website) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{48}
}

func (m *Website) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Website.Unmarshal(m, b)
}
func (m *Website) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Website.Marshal(b, m, deterministic)
}
func (m *Website) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Website.Merge(m, src)
}
func (m *Website) XXX_Size() int {
	return xxx_messageInfo_Website.Size(m)
}
func (m *Website) XXX_DiscardUnknown() {
	xxx_messageInfo_Website.DiscardUnknown(m)
}

var xxx_messageInfo_Website proto.InternalMessageInfo

func (m *Website) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Website) GetContent() map[string]*WebContent {
	if m != nil {
		return m.Content
	}
	return nil
}

type Websites struct {
	Sites                []*Website `protobuf:"bytes,1,rep,name=Sites,proto3" json:"Sites,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Websites) Reset()         { *m = Websites{} }
func (m *Websites) String() string { return proto.CompactTextString(m) }
func (*Websites) ProtoMessage()    {}
func (*Websites) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{49}
}

func (m *Websites) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Websites.Unmarshal(m, b)
}
func (m *Websites) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Websites.Marshal(b, m, deterministic)
}
func (m *Websites) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Websites.Merge(m, src)
}
func (m *Websites) XXX_Size() int {
	return xxx_messageInfo_Websites.Size(m)
}
func (m *Websites) XXX_DiscardUnknown() {
	xxx_messageInfo_Websites.DiscardUnknown(m)
}

var xxx_messageInfo_Websites proto.InternalMessageInfo

func (m *Websites) GetSites() []*Website {
	if m != nil {
		return m.Sites
	}
	return nil
}

func init() {
	proto.RegisterEnum("clientpb.GhostConfig_OutputFormat", GhostConfig_OutputFormat_name, GhostConfig_OutputFormat_value)
	proto.RegisterEnum("clientpb.EggConfig_EggProtocol", EggConfig_EggProtocol_name, EggConfig_EggProtocol_value)
	proto.RegisterType((*File)(nil), "clientpb.File")
	proto.RegisterType((*Process)(nil), "clientpb.Process")
	proto.RegisterType((*Job)(nil), "clientpb.Job")
	proto.RegisterType((*JobKillReq)(nil), "clientpb.JobKillReq")
	proto.RegisterType((*JobKill)(nil), "clientpb.JobKill")
	proto.RegisterType((*Jobs)(nil), "clientpb.Jobs")
	proto.RegisterType((*MTLSReq)(nil), "clientpb.MTLSReq")
	proto.RegisterType((*MTLS)(nil), "clientpb.MTLS")
	proto.RegisterType((*TCPReq)(nil), "clientpb.TCPReq")
	proto.RegisterType((*TCP)(nil), "clientpb.TCP")
	proto.RegisterType((*DNSReq)(nil), "clientpb.DNSReq")
	proto.RegisterType((*DNS)(nil), "clientpb.DNS")
	proto.RegisterType((*HTTPReq)(nil), "clientpb.HTTPReq")
	proto.RegisterType((*HTTP)(nil), "clientpb.HTTP")
	proto.RegisterType((*ProxyReq)(nil), "clientpb.ProxyReq")
	proto.RegisterType((*Proxy)(nil), "clientpb.Proxy")
	proto.RegisterType((*ScanReq)(nil), "clientpb.ScanReq")
	proto.RegisterType((*Scan)(nil), "clientpb.Scan")
	proto.RegisterType((*Ghost)(nil), "clientpb.Ghost")
	proto.RegisterType((*GhostC2)(nil), "clientpb.GhostC2")
	proto.RegisterType((*GhostProxy)(nil), "clientpb.GhostProxy")
	proto.RegisterType((*GhostConfig)(nil), "clientpb.GhostConfig")
	proto.RegisterType((*GhostBuilds)(nil), "clientpb.GhostBuilds")
	proto.RegisterMapType((map[string]*GhostConfig)(nil), "clientpb.GhostBuilds.ConfigsEntry")
	proto.RegisterType((*DNSCanary)(nil), "clientpb.DNSCanary")
	proto.RegisterType((*Canaries)(nil), "clientpb.Canaries")
	proto.RegisterType((*Profile)(nil), "clientpb.Profile")
	proto.RegisterType((*Profiles)(nil), "clientpb.Profiles")
	proto.RegisterType((*Regenerate)(nil), "clientpb.Regenerate")
	proto.RegisterType((*Sessions)(nil), "clientpb.Sessions")
	proto.RegisterType((*GenerateReq)(nil), "clientpb.GenerateReq")
	proto.RegisterType((*Generate)(nil), "clientpb.Generate")
	proto.RegisterType((*MSFReq)(nil), "clientpb.MSFReq")
	proto.RegisterType((*MSFInjectReq)(nil), "clientpb.MSFInjectReq")
	proto.RegisterType((*TaskReq)(nil), "clientpb.TaskReq")
	proto.RegisterType((*MigrateReq)(nil), "clientpb.MigrateReq")
	proto.RegisterType((*GetSystemReq)(nil), "clientpb.GetSystemReq")
	proto.RegisterType((*EggConfig)(nil), "clientpb.EggConfig")
	proto.RegisterType((*EggRequest)(nil), "clientpb.EggRequest")
	proto.RegisterType((*Egg)(nil), "clientpb.Egg")
	proto.RegisterType((*SideloadReq)(nil), "clientpb.SideloadReq")
	proto.RegisterType((*TunnelCreateReq)(nil), "clientpb.TunnelCreateReq")
	proto.RegisterType((*TunnelCreate)(nil), "clientpb.TunnelCreate")
	proto.RegisterType((*TunnelCloseReq)(nil), "clientpb.TunnelCloseReq")
	proto.RegisterType((*Client)(nil), "clientpb.Client")
	proto.RegisterType((*Event)(nil), "clientpb.Event")
	proto.RegisterType((*Players)(nil), "clientpb.Players")
	proto.RegisterType((*Player)(nil), "clientpb.Player")
	proto.RegisterType((*WebContent)(nil), "clientpb.WebContent")
	proto.RegisterType((*Website)(nil), "clientpb.Website")
	proto.RegisterMapType((map[string]*WebContent)(nil), "clientpb.Website.ContentEntry")
	proto.RegisterType((*Websites)(nil), "clientpb.Websites")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 1993 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x18, 0xcb, 0x72, 0xdb, 0xc8,
	0x71, 0xc1, 0x37, 0x9b, 0x92, 0x2c, 0xc3, 0x5a, 0x05, 0xd1, 0x6a, 0xbd, 0x0e, 0x2a, 0x9b, 0xa8,
	0xec, 0xb5, 0x92, 0xc8, 0x79, 0xb8, 0x76, 0x37, 0xa9, 0x92, 0x01, 0x4a, 0xa2, 0x4c, 0x89, 0xdc,
	0x01, 0x1d, 0x27, 0xa7, 0x14, 0x08, 0x8e, 0x29, 0xac, 0x29, 0x80, 0x0b, 0x80, 0xb2, 0x99, 0x1c,
	0xf2, 0x01, 0xf9, 0x86, 0xe4, 0x90, 0x5b, 0x4e, 0x39, 0x27, 0x55, 0x39, 0xe5, 0x94, 0xbf, 0x4a,
	0x75, 0xcf, 0x0c, 0x30, 0x14, 0x45, 0x25, 0xba, 0xed, 0x05, 0xd5, 0xdd, 0xd3, 0xd3, 0xd3, 0xcf,
	0x99, 0x6e, 0xc0, 0x5a, 0x30, 0x09, 0x79, 0x94, 0xed, 0x4f, 0x93, 0x38, 0x8b, 0xcd, 0x86, 0xc0,
	0xa6, 0x43, 0x7b, 0x1f, 0x2a, 0x47, 0xe1, 0x84, 0x9b, 0x26, 0x54, 0xce, 0xfd, 0x4b, 0x6e, 0x19,
	0x8f, 0x8c, 0xbd, 0x26, 0x23, 0x18, 0x69, 0xae, 0x9f, 0xf9, 0x56, 0xe9, 0x91, 0xb1, 0xb7, 0xc6,
	0x08, 0xb6, 0x39, 0xd4, 0xfb, 0x49, 0x1c, 0xf0, 0x34, 0x35, 0x37, 0xa1, 0x3c, 0x0d, 0x47, 0xb4,
	0xa3, 0xca, 0x10, 0xc4, 0x0d, 0x53, 0x24, 0x95, 0x88, 0x44, 0xb0, 0xf9, 0x10, 0x80, 0xbf, 0xe7,
	0xc1, 0x2c, 0xf3, 0x87, 0x13, 0x6e, 0x95, 0x49, 0xbc, 0x46, 0x31, 0xb7, 0xa0, 0x1a, 0xbf, 0x8b,
	0x78, 0x62, 0x55, 0x68, 0x49, 0x20, 0xf6, 0x1f, 0xa0, 0x7c, 0x1a, 0x0f, 0xcd, 0x0d, 0x28, 0x75,
	0x5c, 0x79, 0x42, 0xa9, 0xe3, 0xe6, 0x5a, 0x96, 0x34, 0x2d, 0x1f, 0x41, 0xcb, 0xe5, 0x69, 0x90,
	0x84, 0xd3, 0x2c, 0x8c, 0x23, 0x79, 0x82, 0x4e, 0x32, 0x77, 0xa0, 0xd1, 0x47, 0xb3, 0x83, 0x78,
	0x22, 0x4f, 0xc9, 0x71, 0x94, 0xd8, 0x8f, 0x93, 0xcc, 0xaa, 0x0a, 0x95, 0x11, 0xb6, 0x77, 0x01,
	0x4e, 0xe3, 0xe1, 0xcb, 0x70, 0x32, 0x61, 0xfc, 0x9b, 0xeb, 0x3a, 0xd8, 0x6d, 0xa8, 0xcb, 0xd5,
	0x25, 0xf5, 0x2c, 0xa8, 0x7b, 0xb3, 0x00, 0x9d, 0x43, 0x1a, 0x36, 0x98, 0x42, 0xd1, 0x57, 0xed,
	0x24, 0x91, 0xca, 0x21, 0x68, 0x3f, 0x85, 0xca, 0x69, 0x3c, 0x4c, 0xcd, 0x4f, 0xa1, 0x76, 0x18,
	0x64, 0xe1, 0x15, 0xba, 0xbe, 0xbc, 0xd7, 0x3a, 0x58, 0xdf, 0x57, 0xb1, 0xd9, 0x3f, 0x8d, 0x87,
	0x4c, 0x2e, 0xda, 0xbf, 0x80, 0xfa, 0xd9, 0xa0, 0xeb, 0xa1, 0x42, 0xdb, 0x50, 0xf3, 0x78, 0x72,
	0xc5, 0x13, 0x19, 0x2c, 0x89, 0xa1, 0x27, 0xbb, 0x64, 0x8b, 0x70, 0xbf, 0x40, 0xec, 0x5d, 0xa8,
	0xe0, 0x46, 0x5c, 0x3d, 0x8d, 0x87, 0xb9, 0xba, 0x02, 0xb1, 0x7f, 0x0e, 0xb5, 0x81, 0xd3, 0xbf,
	0xbb, 0xd4, 0x8f, 0xa0, 0x3c, 0x70, 0xfa, 0x2b, 0x84, 0xfe, 0x0a, 0x6a, 0xee, 0x39, 0xa9, 0x6a,
	0x41, 0xdd, 0x8d, 0x2f, 0xfd, 0x30, 0x4a, 0xc9, 0xba, 0x26, 0x53, 0x28, 0xc6, 0xc4, 0xf1, 0x23,
	0x3f, 0x09, 0xb9, 0xf2, 0x55, 0x8e, 0xa3, 0x70, 0xf7, 0x7c, 0x95, 0xc6, 0xff, 0x30, 0xa0, 0x7e,
	0x32, 0x18, 0x28, 0x9d, 0x85, 0x3c, 0xa5, 0xb3, 0xc0, 0x70, 0x67, 0xe7, 0x8d, 0x1f, 0xa8, 0x3c,
	0x11, 0x48, 0x61, 0x49, 0x59, 0xb3, 0x44, 0xd8, 0x1d, 0xcc, 0x12, 0x4e, 0xa9, 0xd1, 0x60, 0x12,
	0x43, 0xd5, 0x5f, 0xf3, 0x61, 0x1a, 0x66, 0x9c, 0x72, 0xa3, 0xc9, 0x14, 0x8a, 0x29, 0xe3, 0xf0,
	0x24, 0xb3, 0x6a, 0xa2, 0x2c, 0x10, 0xc6, 0xf8, 0xbe, 0xe4, 0x73, 0xab, 0x4e, 0x24, 0x04, 0x91,
	0xeb, 0xd0, 0x39, 0x6b, 0x5b, 0x0d, 0x92, 0x4a, 0x30, 0xc6, 0x02, 0x55, 0x5f, 0x61, 0xd9, 0x29,
	0xa5, 0xe9, 0xfb, 0x39, 0x5a, 0x66, 0x42, 0x65, 0x30, 0x9f, 0xe6, 0xe5, 0x88, 0x30, 0xe9, 0x7f,
	0x12, 0xa7, 0x99, 0xb2, 0x8a, 0x90, 0x9b, 0xad, 0xb2, 0x3f, 0x86, 0x2a, 0xc9, 0x5a, 0x71, 0xd4,
	0x6f, 0xa1, 0xee, 0x05, 0x7e, 0x24, 0x4f, 0x3a, 0x4c, 0xc6, 0x2a, 0x3e, 0x04, 0x53, 0x1e, 0x07,
	0x7e, 0x84, 0x55, 0x29, 0xce, 0x52, 0x28, 0x16, 0xdb, 0xeb, 0x38, 0x79, 0x9b, 0x4e, 0xfd, 0x80,
	0x77, 0x5c, 0x55, 0x6c, 0x1a, 0xc9, 0x7e, 0x08, 0x15, 0x64, 0x26, 0xbf, 0x06, 0x7e, 0x94, 0x9f,
	0x2c, 0x31, 0xfb, 0xef, 0x65, 0xa8, 0x1e, 0x5f, 0xa0, 0xe6, 0x45, 0xf5, 0xac, 0xaf, 0x2c, 0xee,
	0x1d, 0x68, 0xa0, 0x95, 0x11, 0xd2, 0xc5, 0x61, 0x39, 0x8e, 0x6b, 0xaf, 0x52, 0x9e, 0xd0, 0x9a,
	0x2c, 0x6b, 0x85, 0x63, 0x3c, 0x5e, 0x75, 0x5c, 0x19, 0x39, 0x04, 0x91, 0x72, 0xdc, 0x71, 0x29,
	0x68, 0x4d, 0x86, 0x20, 0x9e, 0xdf, 0xf3, 0x28, 0x64, 0x4d, 0x56, 0xea, 0x79, 0xc2, 0x13, 0xc1,
	0x05, 0x45, 0x8c, 0x3c, 0x11, 0x5c, 0x98, 0xbb, 0xd0, 0x1c, 0x24, 0x7e, 0x94, 0x4e, 0xd1, 0xc3,
	0x4d, 0x5a, 0x28, 0x08, 0xe6, 0xf7, 0x61, 0x9d, 0xf1, 0xcb, 0x38, 0xe3, 0x87, 0xa3, 0x51, 0x82,
	0x55, 0x0f, 0xc4, 0xb1, 0x48, 0xc4, 0x93, 0xfb, 0x1d, 0xd7, 0x6a, 0x89, 0x7b, 0xb2, 0xdf, 0x71,
	0x51, 0x73, 0xbc, 0x74, 0x49, 0xf3, 0x35, 0xa1, 0xb9, 0xc2, 0xd1, 0xc3, 0x5d, 0x3f, 0xcd, 0x9c,
	0x0b, 0x1e, 0xbc, 0x0d, 0x23, 0x6b, 0x5d, 0x78, 0x58, 0x23, 0xe1, 0x6e, 0x71, 0x29, 0x38, 0x07,
	0xd6, 0x86, 0xd8, 0xad, 0x70, 0x8c, 0xdc, 0xaf, 0x79, 0x92, 0xe2, 0x45, 0x78, 0x4f, 0x44, 0x4e,
	0xa2, 0xd7, 0x23, 0x67, 0x92, 0xdb, 0x75, 0x12, 0x46, 0x0c, 0x7d, 0xdb, 0x71, 0xad, 0xfb, 0xb4,
	0x28, 0x31, 0xfb, 0x2b, 0xa8, 0x53, 0xc0, 0x9c, 0x03, 0x71, 0x93, 0x86, 0x71, 0x12, 0x66, 0x73,
	0x19, 0xb8, 0x1c, 0x27, 0x97, 0xb3, 0xae, 0x8c, 0x1e, 0x82, 0xa8, 0x4c, 0x8f, 0x6e, 0xe0, 0x54,
	0xc6, 0x4e, 0xa1, 0xf6, 0x73, 0x00, 0x12, 0x29, 0x72, 0xf4, 0x2e, 0x3b, 0xff, 0x5c, 0x83, 0x96,
	0xd0, 0x26, 0x8e, 0xde, 0x84, 0x63, 0x0c, 0xda, 0x71, 0xaf, 0xe7, 0xa9, 0x42, 0x41, 0x18, 0x0d,
	0x39, 0xee, 0x1d, 0x32, 0xe7, 0x44, 0x8a, 0x94, 0x58, 0x9e, 0x60, 0x65, 0x2d, 0xc1, 0xb6, 0xa1,
	0xe6, 0x1c, 0x52, 0x39, 0x8b, 0x14, 0x92, 0x58, 0x5e, 0xe4, 0x22, 0x83, 0x16, 0x8a, 0x5c, 0xa6,
	0x10, 0x16, 0xf9, 0x16, 0x54, 0x5d, 0x3e, 0x9c, 0x8d, 0x29, 0x8b, 0x1a, 0x4c, 0x20, 0xe6, 0x63,
	0xd8, 0xec, 0x0d, 0xdf, 0xcc, 0xd2, 0xc0, 0xcf, 0xb8, 0x37, 0xbf, 0x1c, 0xc6, 0x93, 0xd4, 0x7a,
	0x48, 0x0c, 0x4b, 0x74, 0xf3, 0x33, 0xb8, 0xcf, 0x78, 0x10, 0x47, 0x11, 0x0f, 0xb2, 0x4e, 0x94,
	0xf1, 0xe4, 0xca, 0x9f, 0x50, 0x06, 0xae, 0xb3, 0xe5, 0x05, 0xf3, 0xc7, 0xf0, 0xe0, 0xcc, 0x7f,
	0xef, 0x08, 0x6a, 0x18, 0x47, 0xed, 0x24, 0x89, 0x93, 0x94, 0x12, 0x73, 0x9d, 0xdd, 0xb4, 0x64,
	0x7e, 0x0f, 0x4a, 0xce, 0x81, 0x05, 0xf4, 0xb4, 0xdc, 0x2f, 0x9e, 0x16, 0x19, 0x50, 0x56, 0x72,
	0x0e, 0x30, 0x8b, 0xe9, 0xea, 0x9d, 0xab, 0xab, 0xba, 0x45, 0x57, 0xc1, 0x22, 0x11, 0x15, 0xed,
	0x86, 0x97, 0x61, 0x26, 0xf0, 0xd3, 0x38, 0x8c, 0xf8, 0xc8, 0xda, 0x22, 0xab, 0x96, 0x17, 0x50,
	0xa6, 0x20, 0xfa, 0x19, 0xcf, 0xc2, 0x4b, 0x6e, 0x7d, 0x28, 0x2a, 0x63, 0x81, 0x98, 0x73, 0xe5,
	0x25, 0xbe, 0xad, 0x71, 0xe5, 0x75, 0xae, 0xb8, 0xf2, 0x62, 0xff, 0x8e, 0xc6, 0x95, 0x57, 0xfc,
	0xe7, 0x50, 0x3b, 0x8a, 0x93, 0x4b, 0x3f, 0xb3, 0xbe, 0xfb, 0xc8, 0xd8, 0xdb, 0x38, 0xb0, 0xaf,
	0x1b, 0x4b, 0xf9, 0xb2, 0xdf, 0x9b, 0x65, 0xd3, 0x59, 0x26, 0x38, 0x99, 0xdc, 0x81, 0xb5, 0xd1,
	0x49, 0xbd, 0x0b, 0x3f, 0xe1, 0xa3, 0x6e, 0x38, 0xb4, 0x76, 0xc8, 0x2a, 0x9d, 0xb4, 0x50, 0xb1,
	0x1f, 0x2d, 0x57, 0xac, 0x5e, 0x59, 0xbb, 0xcb, 0x95, 0xf5, 0x58, 0xde, 0xc6, 0xd6, 0xc7, 0x14,
	0x87, 0xad, 0x6b, 0xaa, 0x89, 0x5b, 0x5f, 0xb0, 0xd8, 0xbf, 0x84, 0x35, 0x5d, 0x47, 0x73, 0x03,
	0xc0, 0x3b, 0x39, 0x64, 0x6d, 0xf7, 0x77, 0xdd, 0xce, 0x8b, 0xcd, 0x0f, 0xcc, 0x75, 0x68, 0x7a,
	0x27, 0xed, 0x6e, 0xd7, 0xe9, 0xb9, 0xed, 0x4d, 0x03, 0x97, 0xdb, 0xbf, 0x69, 0x3b, 0xaf, 0x06,
	0x87, 0x2f, 0xba, 0xed, 0xcd, 0x92, 0xfd, 0x17, 0x43, 0xd6, 0xc7, 0x8b, 0x59, 0x38, 0x19, 0xa5,
	0xe6, 0x97, 0x50, 0x17, 0x96, 0xa7, 0xb2, 0xbf, 0xb8, 0xee, 0x17, 0xc1, 0xb7, 0x2f, 0x99, 0xda,
	0x51, 0x96, 0xcc, 0x99, 0xda, 0xb2, 0xf3, 0x15, 0xac, 0xe9, 0x0b, 0x58, 0x01, 0x6f, 0xf9, 0x5c,
	0x16, 0x1b, 0x82, 0xe6, 0x13, 0xa8, 0x5e, 0xf9, 0x93, 0x99, 0xb8, 0xb5, 0x5b, 0x07, 0x1f, 0xde,
	0xe8, 0x75, 0x26, 0x78, 0x3e, 0x2f, 0x3d, 0x37, 0xec, 0x7f, 0x1b, 0xd0, 0x74, 0xcf, 0x3d, 0x91,
	0x5c, 0x78, 0xbf, 0x12, 0x9f, 0xd6, 0x7b, 0x16, 0x04, 0xed, 0x7d, 0x2f, 0x2d, 0xbc, 0xef, 0x74,
	0x2b, 0x87, 0xe3, 0x31, 0x4f, 0xf8, 0x88, 0xaa, 0xb9, 0xc1, 0x0a, 0x82, 0xf9, 0x03, 0xd8, 0x38,
	0x0a, 0x93, 0x34, 0x2b, 0x58, 0x44, 0x69, 0x5f, 0xa3, 0x52, 0x5e, 0xf9, 0x19, 0xcf, 0x49, 0xb2,
	0xd6, 0x17, 0x89, 0x58, 0xe2, 0x4e, 0x3c, 0x8b, 0xc4, 0x73, 0xbf, 0xce, 0x04, 0x62, 0x7f, 0x51,
	0xb4, 0x2f, 0xe6, 0x8f, 0xb4, 0x56, 0x46, 0xf8, 0xf8, 0x41, 0xe1, 0x85, 0xdc, 0x54, 0xad, 0xbf,
	0xe9, 0x52, 0x0f, 0xfd, 0x66, 0x55, 0xdb, 0xfd, 0x14, 0x6a, 0xc2, 0x6d, 0xb7, 0xfb, 0x54, 0x32,
	0xd9, 0x3f, 0xa1, 0xb6, 0x01, 0xa5, 0x61, 0x33, 0x59, 0xe9, 0x86, 0x69, 0x26, 0xd5, 0xd0, 0xea,
	0x5d, 0x72, 0x30, 0x5a, 0xb6, 0xcf, 0x01, 0x18, 0x1f, 0xf3, 0x88, 0x27, 0x7e, 0xc6, 0xff, 0x47,
	0x0c, 0x6c, 0x31, 0x20, 0x48, 0x5d, 0x36, 0x0a, 0x91, 0x47, 0x24, 0x0f, 0xbf, 0xf6, 0x33, 0x68,
	0x78, 0x3c, 0xc5, 0x67, 0x26, 0x35, 0x7f, 0x08, 0x35, 0xda, 0xac, 0x7c, 0x71, 0xef, 0x9a, 0xf6,
	0x4c, 0x2e, 0xdb, 0x5f, 0x42, 0xeb, 0x58, 0xaa, 0x80, 0x7d, 0x48, 0x61, 0xb5, 0xf1, 0xff, 0x58,
	0xbd, 0x0f, 0x0d, 0xb5, 0x3b, 0x57, 0xd1, 0xb8, 0x45, 0xc5, 0xbf, 0x1a, 0x50, 0x3b, 0xf3, 0x8e,
	0x64, 0x53, 0xda, 0xf7, 0xe7, 0x93, 0xd8, 0x1f, 0x49, 0x6b, 0x15, 0x7a, 0x97, 0x0e, 0x0b, 0xa5,
	0xb4, 0xa3, 0x20, 0x1e, 0xe5, 0x93, 0x8b, 0x42, 0x71, 0xe2, 0xe9, 0x64, 0xa8, 0x19, 0xbd, 0x5f,
	0x62, 0xb0, 0xd0, 0x28, 0xb8, 0x93, 0x2c, 0xea, 0xb8, 0xf2, 0xe2, 0x56, 0xa8, 0xfd, 0x4f, 0x03,
	0xd6, 0xce, 0xbc, 0xa3, 0x4e, 0xf4, 0x35, 0x0f, 0xb2, 0x6f, 0x83, 0xaa, 0xb2, 0x75, 0x69, 0x14,
	0xad, 0xcb, 0x6a, 0xe5, 0x39, 0xd4, 0x07, 0x7e, 0xfa, 0x56, 0xf6, 0x94, 0x34, 0x38, 0x1a, 0xc5,
	0xe0, 0x88, 0x37, 0x28, 0x7b, 0xf7, 0xbe, 0xef, 0x8f, 0x8b, 0x86, 0x5f, 0xe1, 0x74, 0x4c, 0x28,
	0x2a, 0x79, 0x9d, 0x21, 0x78, 0xcb, 0x31, 0x63, 0x80, 0xb3, 0x70, 0xac, 0xb2, 0x46, 0xee, 0x34,
	0x8a, 0x9d, 0x77, 0xab, 0x1e, 0xfd, 0xa0, 0xf2, 0xe2, 0x41, 0x7f, 0x84, 0xb5, 0x63, 0x9e, 0x79,
	0xf3, 0x34, 0xe3, 0x97, 0x77, 0x4f, 0x50, 0xbc, 0x85, 0x30, 0x24, 0x61, 0x34, 0x96, 0xf3, 0xb2,
	0x8c, 0xd4, 0x35, 0xea, 0x2d, 0x96, 0xfe, 0xc7, 0x80, 0x66, 0x7b, 0x3c, 0x96, 0xf2, 0xbe, 0xd0,
	0x86, 0x58, 0x83, 0x5e, 0xb8, 0x4f, 0x0a, 0x05, 0x72, 0x36, 0x84, 0x14, 0xdb, 0xe2, 0x94, 0xab,
	0x25, 0x0b, 0xc1, 0xf9, 0xe4, 0x2b, 0xcc, 0x26, 0x38, 0x6f, 0x81, 0x2b, 0x5a, 0x0b, 0xbc, 0x9d,
	0x3f, 0xac, 0xe2, 0x7e, 0x94, 0x98, 0xfd, 0x04, 0x5a, 0xda, 0x61, 0x66, 0x9d, 0x26, 0xc2, 0xcd,
	0x0f, 0xcc, 0x86, 0x18, 0x72, 0x36, 0x0d, 0xb3, 0x09, 0x55, 0x84, 0xbc, 0xcd, 0x92, 0xfd, 0x35,
	0x40, 0x7b, 0x3c, 0x66, 0xfc, 0x9b, 0x19, 0x4f, 0xb3, 0xbb, 0xba, 0xf2, 0x29, 0xd4, 0xdb, 0x0b,
	0x31, 0x7d, 0x70, 0x83, 0xe5, 0x4c, 0xf1, 0xd8, 0x2f, 0xa1, 0xdc, 0x1e, 0x8f, 0x57, 0x25, 0x61,
	0xfe, 0x8c, 0x97, 0xae, 0x3d, 0xe3, 0xf9, 0xa4, 0x54, 0xd6, 0x27, 0xa5, 0x3f, 0x19, 0xd0, 0xf2,
	0xc2, 0x11, 0xc7, 0xa2, 0xbb, 0x25, 0xb5, 0x31, 0x9a, 0xda, 0xf0, 0x92, 0xe3, 0xf9, 0x78, 0x55,
	0x56, 0x1e, 0x1d, 0xa7, 0x58, 0x75, 0xf4, 0x9c, 0xf6, 0xe3, 0x30, 0x52, 0x7d, 0xa7, 0x46, 0xd1,
	0x53, 0xa2, 0xba, 0x98, 0x12, 0x4f, 0xe0, 0xde, 0x60, 0x16, 0x45, 0x7c, 0xe2, 0x24, 0x5c, 0x56,
	0x80, 0xc6, 0x6c, 0x2c, 0x32, 0xbb, 0xb0, 0xa6, 0x33, 0xaf, 0xe6, 0x44, 0x03, 0x04, 0xa7, 0x4c,
	0xc2, 0x0a, 0xcb, 0x71, 0xfb, 0x33, 0xd8, 0x90, 0x52, 0x26, 0x71, 0x4a, 0x27, 0xde, 0xc6, 0x7d,
	0x0e, 0x35, 0x87, 0x42, 0x73, 0xd3, 0xaf, 0x1b, 0xec, 0xd5, 0x54, 0x0a, 0x22, 0x7c, 0xd3, 0x34,
	0xb9, 0xd8, 0x39, 0xd9, 0xff, 0x32, 0xa0, 0xda, 0xbe, 0x42, 0x79, 0xbb, 0xd0, 0x24, 0x40, 0x1b,
	0x8b, 0x0b, 0x82, 0xf9, 0xa9, 0x1c, 0x2a, 0x65, 0x82, 0x2c, 0x3d, 0x3a, 0x72, 0xe4, 0xfc, 0x84,
	0x7e, 0x2b, 0xd1, 0x41, 0x4b, 0x7f, 0x5a, 0xe8, 0x87, 0xd3, 0x9e, 0xd2, 0x9f, 0xc2, 0xd2, 0x3a,
	0xd8, 0x2c, 0x78, 0x04, 0x9d, 0x29, 0xfb, 0x54, 0x22, 0x54, 0xb5, 0x44, 0x90, 0x7f, 0x79, 0x9a,
	0xc5, 0x5f, 0x9e, 0x9f, 0x41, 0xbd, 0x3f, 0xf1, 0xe7, 0x3c, 0x49, 0xcd, 0xc7, 0x39, 0x28, 0x5f,
	0x46, 0x4d, 0xb6, 0x58, 0x60, 0x8a, 0xc1, 0xfe, 0x29, 0xd4, 0x04, 0x98, 0xbb, 0xcd, 0xd0, 0xdc,
	0xb6, 0x0d, 0xb5, 0x5e, 0x34, 0x09, 0x23, 0x2e, 0x2f, 0x52, 0x89, 0xd9, 0x53, 0x80, 0xd7, 0x7c,
	0xe8, 0xc4, 0x51, 0x26, 0x15, 0xec, 0xfb, 0xd9, 0x85, 0xda, 0x89, 0x30, 0x3a, 0x5c, 0x2e, 0x93,
	0x1b, 0x45, 0x2c, 0x74, 0x12, 0xee, 0xf2, 0xc2, 0xdf, 0x8b, 0x19, 0xa9, 0xc2, 0x08, 0xc6, 0xc4,
	0x91, 0x2c, 0x64, 0xda, 0x1a, 0x53, 0xa8, 0xfd, 0x37, 0x03, 0xf4, 0xdf, 0x22, 0x4b, 0xad, 0xcc,
	0xf3, 0x62, 0x67, 0x89, 0x6c, 0x7e, 0x58, 0xd8, 0x2c, 0xf7, 0xed, 0x4b, 0x86, 0xa2, 0xf3, 0x44,
	0x6c, 0xa7, 0x4f, 0x9d, 0x67, 0xbe, 0x70, 0x43, 0xe7, 0xf9, 0x78, 0xb1, 0xf3, 0xdc, 0x5a, 0x90,
	0x2c, 0xf7, 0xea, 0x8d, 0xe7, 0x33, 0x68, 0xc8, 0x23, 0xb1, 0x49, 0xa9, 0x7a, 0x08, 0x2c, 0x37,
	0x4a, 0x92, 0x85, 0x89, 0xf5, 0x61, 0x8d, 0xfe, 0x97, 0x3e, 0xfb, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7d, 0xc0, 0x13, 0xc7, 0x3f, 0x15, 0x00, 0x00,
}
